const source = (name) => ({ source: `visual-explainer-mdx/${name}`, destination: name });
const variants = (api, parameter, names) => names.map(name => ({ name, api, parameter }));

// This manifest owns the copy boundary. Implementations remain in their original files.
export const componentRegistry = Object.freeze({
  __sourceFigure: { hidden: true, dependsOn: ['__license'], files: [source('source-figure.tsx'), source('source-document.ts')], dependencies: ['react'], devDependencies: ['@types/react'] },
  __license: {
    hidden: true,
    files: [{ source: 'LICENSE', destination: 'LICENSE' }],
  },
  __punctumGlyphs: {
    hidden: true,
    dependsOn: ['__license'],
    files: ['punctum-text.ts', 'punctum-glyphs.mjs', 'punctum-glyphs.d.mts', 'punctum/bitmaps.json', 'punctum/OFL.txt', 'PUNCTUM-PROVENANCE.md'].map(source),
  },
  'dot-matrix-scene': {
    description: 'Prepare Punctum text as editable five-by-nine dot geometry.',
    capabilities: ['Retain stable character and cell identities', 'Preserve lowercase descenders and explicit line breaks', 'Fit the same prepared scene into posters, diagrams, slides and video', 'Use theme ink or one accent, with an optional unlit lattice'],
    primitives: ['Punctum', 'glyph', 'dot-matrix', 'rect', 'weight', 'roundness', 'lattice'],
    variants: variants('createDotMatrixScene', 'paint', ['ink', 'accent']),
    reuseLevels: ['scene', 'composition', 'poster', 'diagram', 'slide', 'video'],
    delivery: ['Immutable GraphicScene and cell metadata'],
    entryPoints: [{ module: 'dot-matrix', exports: ['createDotMatrixScene'], types: ['DotMatrixInput', 'DotMatrixCell', 'PreparedDotMatrix'] }],
    constraints: ['At most 8 lines of 32 supported characters; unknown glyphs reject. No fallback substitution.', 'Pitch 2–128, weight 100–900, roundness 0–100. SVG dots approximate the font contours.', 'Font data is SIL OFL 1.1; retain punctum/OFL.txt and PUNCTUM-PROVENANCE.md. No font installation required for SVG scenes.'],
    examples: ['examples/visual-explainer-mdx/punctum.tsx', 'examples/visual-explainer-mdx/punctum-source.ts'],
    dependsOn: ['graphics', '__punctumGlyphs'], files: [source('dot-matrix.ts')],
  },
  'character-roll': {
    description: 'Roll old text into new text on a finite, seekable dot display.',
    capabilities: ['Pad both messages into one fixed grid', 'Keep unchanged characters stationary', 'Compile discrete character changes into existing opacity tracks', 'Hold the exact final state and reproduce backward seeks'],
    primitives: ['Punctum', 'character-roll', 'drum', 'stagger', 'step-end', 'finite-clock'],
    variants: [], reuseLevels: ['scene', 'composition', 'slide', 'video'],
    delivery: ['GraphicScene, final scene, GraphicMotion and timed character changes'],
    entryPoints: [{ module: 'character-roll', exports: ['createCharacterRoll'], types: ['CharacterRollInput', 'CharacterRollChange', 'PreparedCharacterRoll'] }],
    constraints: ['1–16 steps; tick ≥ .01s; nonnegative start/stagger and positive final hold. Maximum 120s.', 'Intermediate characters are a display transition, not factual numeric data.', 'Caller supplies authored seconds; reduced motion should show finalScene. No internal playback loop.'],
    examples: ['examples/visual-explainer-mdx/punctum.tsx', 'examples/visual-explainer-mdx/punctum-video.tsx'],
    dependsOn: ['dot-matrix-scene', 'motion'], files: [source('character-roll.ts')],
  },
  'column-scan': {
    description: 'Scan glyph columns with shared visual and optional sound events.',
    capabilities: ['Reveal a message or read an already-visible glyph', 'Highlight each lit cell with one timed accent', 'Generate deterministic WAV clicks from those exact events', 'Reuse the scan through the existing composition, slide and video APIs'],
    primitives: ['Punctum', 'column-scan', 'playhead', 'event', 'frequency', 'PCM', 'WAV'],
    variants: variants('createColumnScan', 'mode', ['reveal', 'read']),
    reuseLevels: ['scene', 'composition', 'slide', 'video'], delivery: ['GraphicScene, GraphicMotion, event list and optional mono WAV'],
    entryPoints: [{ module: 'column-scan', exports: ['createColumnScan'], types: ['ColumnScanInput', 'DotScanEvent', 'PreparedColumnScan'] }, { module: 'scan-audio', exports: ['synthesizeScanWav'], types: ['ScanAudioOptions'] }],
    constraints: ['Scan step ≥ .01s; finite start and positive final hold. Maximum 120s.', 'Sound is opt-in. Preview visuals must use audio currentTime during playback; no second visual clock.', 'Audio is synthesized locally; no upstream score or recordings are copied. Events map glyph row to pitch, not measured data.'],
    examples: ['examples/visual-explainer-mdx/punctum.tsx', 'examples/visual-explainer-mdx/punctum-video.tsx'],
    dependsOn: ['dot-matrix-scene', 'motion'], files: [source('column-scan.ts'), source('scan-audio.ts')],
  },
  'punctum-readout': {
    description: 'Use the canonical Punctum variable font for short display text.',
    capabilities: ['Set caller-owned weight and roundness axes', 'Await actual font readiness before capture', 'Use theme ink or one accent without changing prose fonts'],
    primitives: ['Punctum', 'WOFF2', 'wght', 'ROND', 'display-text'], variants: [],
    reuseLevels: ['page', 'poster', 'slide', 'video'], delivery: ['React text and bundled variable font'],
    entryPoints: [{ module: 'punctum-readout', exports: ['PunctumReadout', 'awaitPunctumFont'], types: ['PunctumReadoutProps'] }],
    constraints: ['Weight 100–900, roundness 0–100, size 8–512. Callers own all animation and time.', 'Display text only; keep body text, code, captions and mathematics on their existing font roles.', 'Canonical unmodified WOFF2 is SIL OFL 1.1. Preserve its notice and await awaitPunctumFont(text).'],
    examples: ['examples/visual-explainer-mdx/punctum.tsx'],
    dependsOn: ['__theme', '__punctumGlyphs'], files: [source('punctum-readout.tsx'), source('punctum-readout.css'), source('punctum/Punctum-VF.woff2')],
    dependencies: ['react'], devDependencies: ['@types/react'],
  },
  __effectMedia: {
    hidden: true,
    dependsOn: ['__license'],
    files: [source('media-source.ts')],
    dependencies: ['react'],
    devDependencies: ['@types/react'],
  },
  __ascii: {
    hidden: true,
    dependsOn: ['__effectMedia'],
    files: [source('ascii-frame.ts')],
  },
  __model: {
    hidden: true,
    dependsOn: ['__ascii'],
    files: ['model-types.ts', 'model-source.ts', 'model-renderer.ts', 'model-view.tsx', 'shape-ascii.ts', 'particle-surface.ts', 'F-EXPLAINER-PROVENANCE.md', 'MODEL-AUTHORING.md'].map(source),
    dependencies: ['three'],
    devDependencies: ['@types/three'],
  },
  'model-view': {
    description: 'Present one editable model factory as shaded geometry, measured ASCII or particles.',
    capabilities: ['Reuse a fresh img2threejs model factory across pages, posters, slides and video', 'Load GLB or decoded image sources with owned readiness and disposal', 'Await a capture-ready frame at explicit seconds', 'Preserve named meshes, pivots, animation closures and semantic paint roles'],
    primitives: ['ModelAsset', 'ModelFactory', 'GLB', 'img2threejs', 'absolute-time', 'six-region', 'point-cloud'],
    variants: variants('ModelView', 'treatment', ['shaded', 'shape-ascii', 'luminance-ascii', 'particles']),
    reuseLevels: ['page', 'poster', 'slide', 'video'],
    delivery: ['Three.js WebGL source', 'Canvas 2D output', 'Awaitable frame controller'],
    entryPoints: [{ module: 'model-view', exports: ['ModelView', 'createModelView', 'modelAsset'], types: ['ModelViewProps'] }, { module: 'model-types', exports: [], types: ['ModelAsset', 'ModelFactory', 'ModelSource', 'ModelFrame', 'ModelFrameReport', 'ModelViewController', 'GlyphMatcherSettings', 'ParticleSettings'] }],
    constraints: ['Factory creates a fresh asset for each view. No cloning, cache protocol or private animation loop.', 'One shared runtime is copied with any model block, including shape matching and point sampling; geometry factories remain separate.', 'WebGL required. Use awaited controller.draw(frame) before capturing pixels; decoded live media remains caller-owned.', 'GLB must be uncompressed with permitted assets. Skin, instance and morph point sampling are explicitly unsupported.'],
    examples: ['examples/visual-explainer-mdx/selected-visuals.tsx'],
    dependsOn: ['__model'], files: [],
  },
  'shape-ascii': {
    description: 'Match measured glyph contours against six local source regions.',
    capabilities: ['Measure a real font atlas and choose the closest six-dimensional glyph', 'Control exposure, directional contrast, inversion and source reveal', 'Apply the same shape treatment to a model factory, GLB or decoded image'],
    primitives: ['glyph-atlas', 'six-region-euclidean', 'coverage', 'source-reveal', 'alpha'],
    variants: [], reuseLevels: ['page', 'poster', 'slide', 'video'],
    delivery: ['Measured Canvas 2D matcher over a WebGL source'],
    entryPoints: [{ module: 'model-view', exports: ['ModelView', 'createModelView'] }, { module: 'model-types', exports: [], types: ['GlyphMatcherSettings'] }],
    constraints: ['Use ModelView treatment="shape-ascii". This measures glyph contours; it is separate from the luminance-ramp sampler.', 'At most 16 distinct glyphs including whitespace. Font preparation is awaited before capture.', 'Canvas output is rendered media; editable geometry stays in the factory or GLB. Keep captions outside the treatment.'],
    examples: ['examples/visual-explainer-mdx/selected-visuals.tsx'],
    dependsOn: ['model-view'], files: [],
  },
  'particle-object': {
    description: 'Sample rigid model surfaces or alpha-aware imagery into deterministic circular points.',
    capabilities: ['Draw points on triangle surfaces without rejecting dark or thin geometry', 'Sample caller-decoded images and live canvas/video alpha', 'Adjust pixel point size and analytic spread while seeking backward exactly', 'Reuse the same model owner, palette and capture-ready frame controller'],
    primitives: ['triangle-area', 'barycentric', 'alpha', 'seed', 'point-size', 'spread'],
    variants: variants('ModelView', 'source.kind', ['geometry', 'gltf', 'image']),
    reuseLevels: ['page', 'poster', 'slide', 'video'], delivery: ['Three.js circular point sprites'],
    entryPoints: [{ module: 'model-view', exports: ['ModelView', 'createModelView'] }, { module: 'model-types', exports: [], types: ['ParticleSettings', 'ModelSource'] }],
    constraints: ['Use ModelView treatment="particles". Original implementation; CanvasUI source/shaders/assets are excluded.', '64–24,000 points. Static geometry and rigid transforms; bake skinned, instanced and morph geometry before sampling.', 'Caller seeks and decodes video before drawing. Pixel sampling requires same-origin or CORS-enabled imagery.'],
    examples: ['examples/visual-explainer-mdx/selected-visuals.tsx'], dependsOn: ['model-view'], files: [],
  },
  'living-forms': {
    description: 'Use the original living-form renderer or editable direct-time model factories.',
    capabilities: ['Compose layered terrain, branching growth and propagating ring metaphors', 'Render any form shaded, shape-aware ASCII or as a point cloud', 'Sample geometry motion from absolute seconds with original camera, material and lights', 'Use the original TSL glyph renderer, Fragment Mono and pointer lighting'],
    primitives: ['strata', 'arbor', 'resonance', 'ModelFactory'],
    variants: [...variants('createLivingForm', 'kind', ['strata', 'arbor', 'resonance']), ...variants('NativeLivingForm', 'form', ['Strata', 'Arbor', 'Resonance'])],
    reuseLevels: ['page', 'poster', 'slide', 'video'], delivery: ['Editable Three.js model factory'],
    entryPoints: [{ module: 'living-forms', exports: ['createLivingForm'] }, { module: 'native-living-forms', exports: ['NativeLivingForm', 'nativeLivingFormSettings'], types: ['NativeLivingFormProps'] }],
    constraints: ['Forms are visual metaphors, not measured charts.', 'Controlled factory declarations sample absolute time; NativeLivingForm preserves the original GPU renderer and accepts optional seconds or its live clock.'],
    examples: ['examples/visual-explainer-mdx/selected-visuals.tsx'], dependsOn: ['model-view'], files: [source('living-forms.ts'), source('native-living-forms.tsx'), source('native-ascii-renderer.tsx'), source('native-living-form-source.ts'), source('native-living-forms.css'), source('FRAGMENT-MONO-OFL.txt')],
    stylesheets: ['native-living-forms.css'],
  },
  'procedural-props': {
    description: 'Use the original clay prop scenes or controlled model factories.',
    capabilities: ['Build named editable meshes from user-selected prop references', 'Preserve original rust, ivory, charcoal materials and soft shadows with NativeProceduralProp', 'Evaluate settling at absolute time and hold an exact rest endpoint', 'Feed the same model through all presentation treatments'],
    primitives: ['boundary-found', 'fair-comparison', 'ready-to-review', 'settle', 'ModelFactory'],
    variants: [...variants('createProceduralProp', 'kind', ['boundary-found', 'fair-comparison', 'ready-to-review']), ...variants('NativeProceduralProp', 'kind', ['boundary-found', 'fair-comparison', 'ready-to-review'])],
    reuseLevels: ['page', 'poster', 'slide', 'video'], delivery: ['Editable Three.js model factory'],
    entryPoints: [{ module: 'procedural-models', exports: ['createProceduralProp'] }, { module: 'native-procedural-props', exports: ['NativeProceduralProp'], types: ['NativeProceduralPropProps'] }],
    constraints: ['The controlled factory samples absolute seconds; NativeProceduralProp samples the original reveal at optional seconds or uses its native clock.', 'Geometry, semantic names and source remain editable. No demo PNG or external texture is copied.'],
    examples: ['examples/visual-explainer-mdx/selected-visuals.tsx'], dependsOn: ['model-view'], files: [source('procedural-models.ts'), source('native-procedural-props.tsx'), source('native-trophy-models.ts'), source('native-trophy-scene.ts')],
  },
  'orbital-text': {
    description: 'Place caller-supplied phrases on finite rotating SVG rings.',
    capabilities: ['Use alternating phrase rings and one accented ring', 'Seek typography at explicit seconds', 'Keep accessible labels and editable vector text without a GPU'],
    primitives: ['textPath', 'phrase', 'ring', 'rotation'], variants: [],
    reuseLevels: ['page', 'poster', 'slide', 'video'], delivery: ['React SVG'],
    entryPoints: [{ module: 'orbital-text', exports: ['OrbitalText'], types: ['OrbitalTextProps', 'OrbitalTextPalette'] }],
    constraints: ['3–32 rings and 1–32 phrases. Explicit seconds; no internal clock.', 'Caller supplies palette, accessible label and stationary seconds for reduced motion.'],
    examples: ['examples/visual-explainer-mdx/selected-visuals.tsx'], dependsOn: ['__license'],
    files: [source('orbital-text.tsx'), source('F-EXPLAINER-PROVENANCE.md')], dependencies: ['react'], devDependencies: ['@types/react'],
  },
  'trace-path': {
    description: 'Reveal an SVG path from controlled normalized progress.',
    capabilities: ['Draw a line or curve without measuring its length', 'Hide zero and reveal the exact full endpoint without a dash seam', 'Use ordinary SVG stroke props while retaining reveal ownership'],
    primitives: ['pathLength', 'progress', 'stroke-reveal'], variants: [],
    reuseLevels: ['page', 'poster', 'slide', 'video'], delivery: ['React SVG path'],
    entryPoints: [{ module: 'trace-path', exports: ['TracePath'], types: ['TracePathProps', 'TracePathStyle'] }],
    constraints: ['Progress from 0–1; dash policy is owned by the component.', 'For GraphicScene use the existing GraphicMotion reveal track instead of this SVG leaf.'],
    examples: ['examples/visual-explainer-mdx/selected-visuals.tsx'], dependsOn: ['__license'],
    files: [source('trace-path.tsx'), source('F-EXPLAINER-PROVENANCE.md')], dependencies: ['react'], devDependencies: ['@types/react'],
  },
  'ascii-image': {
    description: 'Sample media into a bounded, two-ink ASCII frame.',
    capabilities: ['Convert same-origin images, SVG images, canvases and caller-seeked videos into glyph cells', 'Preserve one cyan accent and transparent background', 'Use the same renderer for a still or an explicit-time frame'],
    primitives: ['luminance', 'glyph-ramp', 'cell-grid', 'transparency', 'accent'],
    variants: [],
    reuseLevels: ['page', 'poster', 'slide', 'video'],
    delivery: ['React Canvas 2D'],
    entryPoints: [{ module: 'ascii-effects', exports: ['AsciiImage'], types: ['AsciiImageProps'] }, { module: 'ascii-frame', exports: ['createAsciiFrame'], types: ['AsciiPalette', 'AsciiFrameOptions'] }, { module: 'media-source', exports: [], types: ['EffectSource'] }],
    constraints: ['Luminance ramp, not the shape-aware f-explainer matcher. Up to 240×135 cells and 2,073,600 frame pixels.', 'Explicit seconds redraw a live source; the caller seeks and decodes video media first.', 'URL media must be same-origin or CORS-enabled. No experimental HTML-in-canvas capture.', 'Palette is caller-supplied; keep labels and text outside the effect canvas.'],
    examples: ['examples/visual-explainer-mdx/media-effects.tsx'],
    dependsOn: ['__ascii'],
    files: [source('ascii-effects.tsx')],
  },
  'ascii-sweep': {
    description: 'Reveal a second image through a deterministic glyph band.',
    capabilities: ['Wipe between two media sources at explicit progress', 'Use four sweep directions and a seeded irregular edge', 'Preserve exact uneffected start and end frames'],
    primitives: ['wipe', 'glyph-band', 'seed', 'progress'],
    variants: variants('AsciiSweep', 'direction', ['right', 'left', 'up', 'down']),
    reuseLevels: ['page', 'poster', 'slide', 'video'],
    delivery: ['React Canvas 2D'],
    entryPoints: [{ module: 'ascii-effects', exports: ['AsciiSweep'], types: ['AsciiSweepProps'] }],
    constraints: ['Progress is controlled from 0–1; no internal animation loop.', 'Image/canvas/video sources, not arbitrary DOM children. Convert diagrams to an image or render target first.', 'Independent implementation inspired by CanvasUI behavior; no CanvasUI source is redistributed.'],
    examples: ['examples/visual-explainer-mdx/media-effects.tsx'],
    dependsOn: ['ascii-image'],
    files: [],
  },
  'ascii-object': {
    description: 'Render a glTF model or prepared geometry through the shared model owner and luminance sampler.',
    capabilities: ['Load an uncompressed Blender-exported GLB', 'Fit model bounds and light a turntable', 'Sample glTF animation and rotation at explicit seconds', 'Switch between shaded geometry and glyph output'],
    primitives: ['GLB', 'glTF', 'orthographic-camera', 'AnimationMixer', 'torus-knot', 'icosahedron', 'blocks'],
    variants: variants('AsciiObject', 'model.kind', ['geometry', 'gltf']),
    reuseLevels: ['page', 'poster', 'slide', 'video'],
    delivery: ['Three.js WebGL scene sampled into Canvas 2D'],
    entryPoints: [{ module: 'ascii-object', exports: ['AsciiObject'], types: ['AsciiModel', 'AsciiObjectProps'] }],
    constraints: ['WebGL required. No internal RAF; caller supplies seconds. Reduced motion uses a stationary pose.', 'Uncompressed glTF only; Draco/KTX decoders are not fetched automatically. Embedded textures preferred.', 'Native Blender stays an optional authoring tool; retain .blend source and asset license. See docs/media-effects.md.'],
    examples: ['examples/visual-explainer-mdx/media-effects.tsx'],
    dependsOn: ['model-view'],
    files: [source('ascii-object.tsx'), { source: 'examples/media-native/blender-blocks.py', destination: 'blender-blocks.py' }],
  },
  vhs: {
    description: 'Apply a bounded analogue texture treatment to prepared media.',
    capabilities: ['Sample row drift, a rolling crease, RGB separation, scanlines and seeded grain', 'Freeze decorative motion for reduced-motion preference', 'Compose image/canvas/video input without capturing live DOM'],
    primitives: ['scanlines', 'grain', 'aberration', 'row-drift', 'crease'],
    variants: [],
    reuseLevels: ['page', 'poster', 'slide', 'video'],
    delivery: ['React WebGL texture filter'],
    entryPoints: [{ module: 'vhs-effect', exports: ['VhsEffect'], types: ['VhsEffectProps'] }, { module: 'vhs-renderer', exports: ['createVhsRenderer'], types: ['VhsSettings'] }],
    constraints: ['Explicit seconds; no accumulated random state or private loop.', 'WebGL required; use original media when unavailable. Source must allow pixel sampling.', 'Filter imagery only; put captions and labels after the filter.', 'Independent shader, not a port of CanvasUI VHS.'],
    examples: ['examples/visual-explainer-mdx/media-effects.tsx'],
    dependsOn: ['__effectMedia'],
    files: [source('vhs-effect.tsx'), source('vhs-renderer.ts')],
  },
  __lemoLicense: {
    hidden: true,
    dependsOn: ['__license'],
    files: [source('LEMO-LICENSE')],
  },
  __theme: {
    hidden: true,
    dependsOn: ['__license'],
    files: [source('themes.css')],
    stylesheets: ['themes.css'],
  },
  __code: {
    hidden: true,
    dependsOn: ['__theme'],
    files: [source('code-blocks.tsx'), source('code-blocks.css'), source('diff-lines.mjs'), source('diff-lines.d.mts')],
    dependencies: ['react'],
    devDependencies: ['@types/react'],
  },
  __content: {
    hidden: true,
    dependsOn: ['__theme'],
    files: [source('content-blocks.tsx'), source('content-blocks.css')],
    dependencies: ['react'],
    devDependencies: ['@types/react'],
  },
  __threads: {
    hidden: true,
    dependsOn: ['__theme'],
    files: [source('lieflat-threads.tsx'), source('lieflat-threads.css'), source('lieflat-types.ts')],
    dependencies: ['react'],
    devDependencies: ['@types/react'],
  },
  __teachingScenes: {
    hidden: true,
    dependsOn: ['graphics'],
    files: [source('teaching-scenes.ts')],
  },
  __teachingMotion: {
    hidden: true,
    dependsOn: ['motion'],
    files: [source('teaching-motion.ts')],
  },
  'native-clip': {
    description: 'Reuse native Manim and Psychopomp output as video clips and selected stills.',
    capabilities: ['Play a rendered Manim or Psychopomp clip in docs', 'Place native media on a HyperFrames timeline', 'Reuse exact decoded frames in posters and slides', 'Validate explicit media ranges and frame provenance'],
    primitives: ['clip', 'poster', 'still', 'placement', 'mediaStart', 'encoded-frame'],
    variants: variants('NativeClip', 'asset.engine', ['manim', 'psychopomp', 'source']),
    reuseLevels: ['page', 'poster', 'slide', 'video'],
    delivery: ['React video or image', 'HyperFrames timed media element'],
    entryPoints: [{ module: 'native-clip', exports: ['NativeClip', 'NativeStill', 'validateNativeClipAsset'], types: ['NativeClipAsset', 'NativeClipPlacement'] }],
    constraints: ['Supply manifest.asset from artifacture engine render and an explicit asset base URL.', 'Native geometry remains editable in Python or Rust source; it is not converted to browser SVG.', 'A composition placement gives media playback to HyperFrames; it does not start another clock.', 'Use an exact requested still time; an unrendered pose rejects.'],
    examples: ['examples/visual-explainer-mdx/native-engines.tsx'],
    dependsOn: ['__license'],
    files: [source('native-clip.tsx'), source('native-asset.ts')],
    dependencies: ['react'],
    devDependencies: ['@types/react'],
  },
  'manim-clip': {
    description: 'Copy an editable native mathematical animation and its render job.',
    capabilities: ['Explain a secant approaching a tangent', 'Typeset real formulas with MathTypst', 'Animate a tracked parameter and matching formula shapes', 'Use pinned Manim Community through artifacture engine render'],
    primitives: ['MathTypst', 'Axes', 'ValueTracker', 'TransformMatchingShapes', 'Scene'],
    variants: variants('artifacture engine render', 'theme', ['iso', '3b1b', 'mono-color', 'algebrica']),
    reuseLevels: ['native source', 'page', 'poster', 'slide', 'video'],
    delivery: ['Python scene source and job JSON', 'NativeClip and NativeStill'],
    entryPoints: [{ module: 'native-clip', exports: ['NativeClip', 'NativeStill'] }],
    constraints: ['Run artifacture engine setup manim once; native Python, Cairo/Pango and FFmpeg are separate from npm.', 'The pinned Manim/Typst runtime typesets formulas without a system TeX installation.', 'Render the copied manim.job.json; frames are opaque H.264, not editable SVG.'],
    examples: ['scripts/video-engines/templates/secant-to-tangent.py', 'scripts/video-engines/templates/manim.job.json'],
    dependsOn: ['native-clip'],
    files: [{ source: 'scripts/video-engines/templates/secant-to-tangent.py', destination: 'secant-to-tangent.py' }, { source: 'scripts/video-engines/templates/manim.job.json', destination: 'manim.job.json' }],
  },
  'psychopomp-clip': {
    description: 'Copy an editable physical diagram and its native render job.',
    capabilities: ['Settle connected diagram cards on native springs', 'Draw bowed connections and send named packets', 'Land a packet and let its cable settle', 'Emit and validate an inspectable Scene Plan', 'Use pinned Psychopomp through artifacture engine render'],
    primitives: ['StagePlan', 'StageActor', 'card', 'beam', 'packet', 'settle_in', 'connect', 'send', 'land', 'twang'],
    variants: variants('artifacture engine render', 'theme', ['iso', '3b1b', 'mono-color', 'algebrica']),
    reuseLevels: ['native source', 'page', 'poster', 'slide', 'video'],
    delivery: ['Rust scene source and job JSON', 'Scene Plan', 'NativeClip and NativeStill'],
    entryPoints: [{ module: 'native-clip', exports: ['NativeClip', 'NativeStill'] }],
    constraints: ['Run artifacture engine setup psychopomp once; the first Rust/wgpu build and a compatible GPU are required.', 'The integration applies a bounded paint-only theme bridge to a pinned MIT upstream source.', 'Native source is a single Rust Scene Program; additional crate integrations remain upstream capabilities.', 'Psychopomp renders at 1080p/60 fps internally; delivery is normalized to the job settings.'],
    examples: ['scripts/video-engines/templates/psychopomp.rs', 'scripts/video-engines/templates/psychopomp.job.json'],
    dependsOn: ['native-clip'],
    files: [{ source: 'scripts/video-engines/templates/psychopomp.rs', destination: 'psychopomp.rs' }, { source: 'scripts/video-engines/templates/psychopomp.job.json', destination: 'psychopomp.job.json' }],
  },
  graphics: {
    description: 'Render validated scene data as accessible React SVG.',
    capabilities: ['Draw rectangles, circles, polygons, paths, lines, arrows, and readable text', 'Validate and freeze editable GraphicScene data', 'Render accessible SVG with theme paint, font, and stroke roles'],
    primitives: ['rect', 'circle', 'polygon', 'path', 'line', 'text', 'arrow:end', 'arrow:both'],
    variants: [...variants('createGraphicScene', 'objects[].primitives[].kind', ['rect', 'circle', 'polygon', 'path', 'line', 'text']), ...variants('createGraphicScene', 'objects[].primitives[].arrow', ['end', 'both'])],
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['React SVG'],
    entryPoints: [
      { module: 'graphics', exports: ['GraphicCanvas', 'createGraphicScene'] },
      { module: 'graphics-types', exports: ['createGraphicScene', 'validateGraphicScene', 'validateGraphicBounds'], types: ['GraphicBounds', 'GraphicPlacement', 'GraphicClip', 'GraphicPaint', 'GraphicFont', 'GraphicStrokeRole', 'GraphicPrimitive', 'GraphicObject', 'GraphicScene'] },
    ],
    constraints: ['Closed SVG primitive data; no arbitrary SVG markup or custom renderer.', 'Render inside a host that imports themes.css.'],
    examples: ['examples/visual-explainer-mdx/shared-graphics-poster.tsx', 'examples/visual-explainer-mdx/shared-graphics-source.ts'],
    dependsOn: ['__theme'],
    files: [source('graphics-types.ts'), source('graphics.tsx')],
    dependencies: ['react'],
    devDependencies: ['@types/react'],
  },
  diagram: {
    description: 'Lay out nodes and edges as a reusable scene.',
    capabilities: ['Build GraphicScene data from nodes and relationships', 'Lay out flow, tree, swimlane, and timeline diagrams', 'Author separate horizontal and vertical layouts', 'Route labeled, dashed, and bidirectional edges'],
    primitives: ['rect', 'oval', 'diamond', 'dot', 'node', 'edge', 'lane', 'tick'],
    variants: [...variants('createDiagramScene', 'layout', ['flow', 'tree', 'swimlane', 'timeline']), ...variants('createDiagramScene', 'direction', ['auto', 'horizontal', 'vertical']), ...variants('createDiagramScene', 'nodes[].shape', ['rect', 'oval', 'diamond', 'dot'])],
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['GraphicScene data', 'React SVG through GraphicCanvas'],
    entryPoints: [{ module: 'diagram-design-figure', exports: ['DiagramDesignFigure', 'diagramDesignExamples', 'diagramDesignSource'], types: ['DiagramDesignFigureProps', 'DiagramDesignExample'] },
      { module: 'diagram-scene', exports: ['createDiagramScene', 'diagramSceneFromLayout'] },
      { module: 'diagram-types', exports: [], types: ['DiagramNodeGlyph', 'DiagramNode', 'DiagramEdge', 'DiagramLane', 'DiagramCanvasProps'] },
    ],
    constraints: ['Layout is resolved when the scene is created; choose responsive variants outside the motion sampler.', 'For the ready React view choose diagram-canvas; for step playback choose diagram-walkthrough.'],
    examples: ['examples/visual-explainer-mdx/shared-graphics-source.ts', 'examples/visual-explainer-mdx/shared-graphics-poster.tsx'],
    dependsOn: ['__sourceFigure', 'graphics'],
    files: [source('diagram-design-figure.tsx'), source('diagram-design-examples.ts'), source('DIAGRAM-DESIGN-LICENSE'), source('diagram-types.ts'), source('diagram-layout.ts'), source('diagram-scene.ts')],
  },
  dag: {
    description: 'Show a compact dependency graph with a focusable list and reusable scene geometry.',
    capabilities: ['Lay out disconnected roots and multi-parent merges with d3-dag grid', 'Validate dependencies and report an actual cycle path', 'Trace immediate parents and children or full upstream/downstream lineage', 'Explore with pointer, keyboard or touch while sharing one theme accent', 'Reuse the labeled scene as a poster or slide, or reveal dependencies on the shared motion sampler', 'Produce a card-and-arrow variant through the existing diagram layout'],
    primitives: ['parentIds', 'node', 'edge', 'root', 'merge', 'topological-order', 'lineage', 'reveal'],
    variants: [...variants('DagCanvas', 'scope', ['neighbors', 'lineage']), ...variants('createDagDiagram', 'direction', ['horizontal', 'vertical'])],
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['Interactive React DAG', 'GraphicScene data', 'Finite GraphicMotion data'],
    entryPoints: [{ module: 'dag-canvas', exports: ['DagCanvas'], types: ['DagCanvasProps'] }, { module: 'dag-scene', exports: ['prepareDag', 'createDagScene', 'createDagDiagram', 'dagNeighborhood', 'focusDagScene', 'createDagReveal'], types: ['DagNode', 'DagInput', 'DagEdge', 'PreparedDag', 'DagNeighborhood'] }],
    constraints: ['1–256 nodes, at most 2048 edges. IDs and parent IDs must be unique; unknown parents, self loops and cycles reject.', 'Stable input order resolves ties between ready nodes; dependencies may be supplied out of order.', 'The compact view has one labeled row per node; scrolling preserves legible text instead of shrinking the graph.', 'The scene and its reveal use authored time. DagCanvas supplies focus controls, not a separate animation clock.', 'The interaction is independently authored from the supplied Svelte reference; no Svelte runtime or playground source is copied.'],
    examples: ['examples/visual-explainer-mdx/dag.tsx', 'examples/visual-explainer-mdx/dag-source.ts'],
    dependsOn: ['diagram', 'motion'],
    files: [source('dag-scene.ts'), source('dag-canvas.tsx'), source('dag-canvas.css')],
    dependencies: ['d3-dag'],
  },
  iso: {
    description: 'Build reusable isometric objects with face-local detail and causal lighting.',
    capabilities: ['Project three visible rounded faces into shared path primitives', 'Fit projected rest geometry with a numeric margin', 'Paint caller-composed parts back to front', 'Light one active part using the host accent and a scoped glow', 'Reuse geometry through compositions, posters, slides and both video renderers'],
    primitives: ['isometric', '30-degree', 'top', 'front', 'side', 'window', 'vent', 'live', 'glow'],
    variants: variants('createIsoScene', 'parts[].details[].face', ['top', 'front', 'side']),
    reuseLevels: ['scene', 'composition', 'poster', 'diagram', 'slide', 'video'],
    delivery: ['GraphicScene data', 'React SVG through GraphicCanvas'],
    entryPoints: [{ module: 'iso-scene', exports: ['createIsoScene', 'projectIsoPoint'], types: ['IsoPoint', 'IsoFace', 'IsoDetail', 'IsoPart', 'IsoSceneInput'] }],
    constraints: ['1–128 parts, at most one active part, 256 details per part; face details must fit their plane.', 'Painter order is x+y then z, not arbitrary intersecting-solid occlusion; compose nonintersecting parts and check extreme poses.', 'Rest bounds are fitted automatically; provide a larger frame for motion excursions.', 'Only live face details glow; the shared theme owns the accent; the portable SVG halo uses 2.3 local units. Keep both MIT notices beside the source.'],
    examples: ['examples/visual-explainer-mdx/iso.tsx', 'examples/visual-explainer-mdx/iso-source.ts', 'examples/visual-explainer-mdx/iso-video.tsx'],
    dependsOn: ['graphics'], files: ['iso-scene.ts', 'ISO-FIGURE-LICENSE', 'ISO-GLOW-LICENSE', 'ISO-PROVENANCE.md'].map(source),
  },
  'motion-eases': {
    description: 'Sample bounded Motionmaxxing landing and exit curves without a playback clock.',
    capabilities: ['Decelerate arrivals and accelerate departures', 'Keep exact endpoints and deterministic backward seeks', 'Share the same named curves with GraphicMotion'],
    primitives: ['soft-land', 'snap-settle', 'glide', 'whip', 'soft-in-out', 'gentle-in', 'accel-exit', 'crash-out'],
    variants: variants('sampleMotionEase', 'ease', ['linear', 'smooth', 'soft-land', 'snap-settle', 'glide', 'whip', 'soft-in-out', 'gentle-in', 'accel-exit', 'crash-out']),
    reuseLevels: ['scene', 'composition', 'slide', 'video'], delivery: ['Normalized scalar progress'],
    entryPoints: [{ module: 'motion-eases', exports: ['motionEaseNames', 'sampleMotionEase'], types: ['MotionEase'] }],
    constraints: ['Finite progress clamps to exact 0/1 endpoints; unknown names reject.', 'Eight monotone upstream curves are adapted; overshooting/spring curves and the GSAP runtime are excluded.', 'Keep the Apache-2.0 license and NOTICE beside copied source.'],
    examples: ['examples/visual-explainer-mdx/iso-source.ts'],
    dependsOn: ['__license'], files: ['motion-eases.ts', 'MOTIONMAXXING-LICENSE', 'MOTIONMAXXING-NOTICE'].map(source),
  },
  shaders: {
    description: 'Use the original Shader Effects WebGPU components and controlled native shader surfaces.',
    capabilities: ['Compose the full official React shader library', 'Sample original Plasma, SimplexNoise and Spiral at explicit seconds', 'Await GPU completion before capturing a frame'],
    primitives: ['WebGPU', 'native-shader', 'absolute-time', 'gradient', 'noise', 'material', 'transition'],
    variants: variants('NativeShader', 'effect', ['Plasma', 'SimplexNoise', 'Spiral']),
    reuseLevels: ['page', 'poster', 'slide', 'video'],
    delivery: ['Original WebGPU React components', 'Awaitable native GPU frame controller'],
    entryPoints: [{ module: 'shader-components', exports: ['Shader', 'LinearGradient', 'RadialGradient', 'MeshGradient', 'Plasma', 'SimplexNoise', 'Spiral', 'Aurora', 'Glass', 'LiquidMetal', 'ThinFilm', 'Chrome', 'Dither', 'Halftone', 'Ascii', 'FilmGrain', 'VHS', 'CursorTrail', 'CursorRipples', 'LinearWipe'] }, { module: 'native-shader', exports: ['NativeShader'], types: ['NativeShaderProps'] }, { module: 'shader-surface', exports: ['createShaderSurface', 'shaderEffects'], types: ['ShaderEffect', 'ShaderSurfaceProps', 'ShaderSurfaceSettings', 'ShaderSurfaceController'] }],
    constraints: ['WebGPU required; failure is reported without substituting a different effect.', 'The full original library keeps native live behavior. Explicit-time capture supports Plasma, SimplexNoise and Spiral with fixed props; stateful simulations and cursor effects require their native recording workflow.', 'Original shader defaults and GPU code are preserved. Platform presets/editor assets are separate and excluded.'],
    examples: ['examples/visual-explainer-mdx/shaders.tsx'],
    dependsOn: ['__license'],
    files: [source('shader-components.ts'), source('shader-surface.ts'), source('native-shader.tsx'), source('SHADERS-LICENSE'), source('TYPEGPU-LICENSE'), source('COLORJS-LICENSE')],
    dependencies: ['react', 'shaders'],
    devDependencies: ['@types/react'],
  },
  hairline: {
    description: 'Use the original 27 interactive Hairline figures or adapt prepared paths into a scene.',
    capabilities: ['Use the original 27 pointer-responsive figures from Lucas Markes', 'Preserve native camera, fillets, occlusion, springs, keyboard input and cleanup', 'Prepare GraphicScene illustration objects from caller-authored paths'],
    primitives: ['sil', 'crease', 'illustration'],
    variants: [],
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['Original interactive Hairline React figures', 'GraphicScene data', 'React SVG through GraphicCanvas'],
    entryPoints: [{ module: 'hairline-figures', exports: ['Riffle', 'Terrain', 'Exploded', 'Phosphor', 'Slow', 'Turntable', 'Keyboard', 'Elevator', 'Phone', 'Laptop', 'Terminal', 'Cabinet', 'Branches', 'Vault', 'Lockers', 'Loupe', 'Padlock', 'Patch', 'Dish', 'Router', 'Sieve', 'Rail', 'Plug', 'Query', 'Drawer', 'Basket', 'Plot'], types: ['HairlineProps'] }, { module: 'hairline-scene', exports: ['createHairlineScene'], types: ['HairlineSolid'] }],
    constraints: ['Interactive figures use the pinned official MIT package; their native pointer behavior is separate from authored scene time.', 'The prepared-path adapter remains available for authored scenes; it is not the interactive engine.'],
    examples: ['examples/visual-explainer-mdx/source-libraries.tsx', 'examples/visual-explainer-mdx/motion-review.tsx', 'examples/visual-explainer-mdx/motion-review-source.ts', 'examples/visual-explainer-mdx/showcase-hairline.ts'],
    dependsOn: ['graphics'],
    files: [source('hairline-scene.ts'), source('hairline-figures.ts')],
    dependencies: ['@lucasmarkes/hairline'],
  },
  motion: {
    description: 'Define and sample finite scene motion at explicit time.',
    capabilities: ['Query deterministic frames at authored seconds', 'Fade object opacity', 'Reveal paths', 'Focus objects with highlight', 'Translate illustrations along linear or prepared routes', 'Intersect authored rectangular masks with base clips', 'Author exact discrete cue boundaries and meaningful holds'],
    primitives: ['opacity', 'reveal', 'highlight', 'translation', 'route', 'mask', 'linear', 'smooth', 'step-end', 'soft-land', 'snap-settle', 'accel-exit'],
    variants: [...variants('defineGraphicMotion', 'tracks[].property', ['opacity', 'reveal', 'highlight', 'translation', 'route', 'mask']), ...variants('defineGraphicMotion', 'tracks[].ease', ['linear', 'smooth', 'soft-land', 'snap-settle', 'glide', 'whip', 'soft-in-out', 'gentle-in', 'accel-exit', 'crash-out'])],
    reuseLevels: ['scene', 'composition', 'slide', 'video'],
    delivery: ['Sampled GraphicScene data'],
    entryPoints: [{ module: 'graphic-motion', exports: ['defineGraphicMotion', 'sampleScene'], types: ['GraphicMotionTrack', 'GraphicMotion'] }],
    constraints: ['Translation and route motion support illustration objects only and share one conflict channel; relayout diagram nodes with createDiagramScene.', 'Reveal supports path-only objects. Masks use resolved scene coordinates and intersect base clips.', 'Finite authored time only; no hidden clock, overlapping writes to one channel, or spring simulation.'],
    examples: ['examples/visual-explainer-mdx/shared-graphics-source.ts', 'examples/visual-explainer-mdx/shared-graphics-video.tsx'],
    dependsOn: ['graphics', 'motion-eases'],
    files: [source('graphic-motion.ts'), source('graphic-routes.ts'), source('graphic-clips.ts')],
  },
  'axonometric-plan': {
    description: 'Project a floor or site into a shaded, editable SVG plan.',
    capabilities: ['Generate rounded slabs, walls, furniture and buildings from model coordinates', 'Resolve back-to-front occlusion topologically, including long walls', 'Name rooms or roofs with horizontal tags and one focal element', 'Reveal at most two boxes per authored phase on the existing motion sampler'],
    primitives: ['2:1-dimetric', 'plate', 'rounded-prism', 'flat-mark', 'roof-tag', 'phase'],
    variants: [], reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['GraphicScene data', 'Finite GraphicMotion data', 'React SVG through GraphicCanvas'],
    entryPoints: [{ module: 'diagram-design-figure', exports: ['DiagramDesignFigure', 'diagramDesignExamples', 'diagramDesignSource'], types: ['DiagramDesignFigureProps', 'DiagramDesignExample'] }, { module: 'axonometric-scene', exports: ['projectAxonometric', 'createAxonometricPlan', 'createAxonometricPlanMotion'], types: ['AxonometricRect', 'AxonometricBox', 'AxonometricMark', 'AxonometricPlanInput'] }],
    constraints: ['1–48 elements on one plate; box footprints and horizontal tags must not overlap. Occlusion cycles reject.', 'Labels default to 20 model units; author a compact layout or raise labelSize to retain at least 14px at display size.', 'Static scene is the finished plan. Motion is opt-in, explicit-time and finite; no internal clock or WebGL.'],
    examples: ['examples/visual-explainer-mdx/axonometric.tsx', 'examples/visual-explainer-mdx/axonometric-source.ts'],
    dependsOn: ['__sourceFigure', 'motion'], files: [source('diagram-design-figure.tsx'), source('diagram-design-examples.ts'), source('DIAGRAM-DESIGN-LICENSE'), source('axonometric-scene.ts')],
  },
  'exploded-axonometric': {
    description: 'Use original Diagram Design exploded documents or a compact shared-clock assembly adapter.',
    capabilities: ['Preserve all original exploded geometry, skin and native controls with DiagramDesignFigure', 'Project 2–5 rounded parts with shared assembly levels', 'Split tray back and front walls around contained parts for correct closed-frame occlusion', 'Resolve equal lift gaps and horizontal part leaders', 'Lift upper levels first and reveal names after each level settles', 'Reuse the completed scene as a still, slide or finite video frame'],
    primitives: ['2:1-dimetric', 'rounded-prism', 'tray', 'shared-level', 'leader', 'explode'],
    variants: variants('createExplodedScene', 'parts[].kind', ['solid', 'tray']),
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['GraphicScene data', 'Finite GraphicMotion data', 'React SVG through GraphicCanvas'],
    entryPoints: [{ module: 'diagram-design-figure', exports: ['DiagramDesignFigure', 'diagramDesignExamples', 'diagramDesignSource'], types: ['DiagramDesignFigureProps', 'DiagramDesignExample'] }, { module: 'axonometric-scene', exports: ['projectAxonometric', 'createExplodedScene', 'createExplodedMotion'], types: ['AxonometricRect', 'ExplodedPart', 'ExplodedSceneInput'] }],
    constraints: ['2–5 physical parts; contiguous integer levels from zero. Parts sharing a level lift together.', 'Assembled intersections reject except contents inside a tray. Equal gaps expand for leader/label clearance; move conflicting same-level parts in plan.', 'Static scene is fully exploded; caller owns playback, reduced motion and print frames. The bottom level stays fixed.'],
    examples: ['examples/visual-explainer-mdx/axonometric.tsx', 'examples/visual-explainer-mdx/axonometric-source.ts'],
    dependsOn: ['__sourceFigure', 'motion'], files: [source('diagram-design-figure.tsx'), source('diagram-design-examples.ts'), source('DIAGRAM-DESIGN-LICENSE'), source('axonometric-scene.ts')],
  },
  composition: {
    description: 'Fit reusable scenes into frames with one shared timeline.',
    capabilities: ['Compose independent reusable scene instances', 'Fit scenes uniformly into frames', 'Scope object and relationship identities', 'Bind instance motion to one finite authored timeline'],
    primitives: ['instance', 'frame', 'clip:none', 'clip:frame', 'align:start', 'align:center', 'align:end'],
    variants: [...variants('composeGraphics', 'instances[].clip', ['none', 'frame']), ...variants('composeGraphics', 'instances[].align.x', ['start', 'center', 'end']), ...variants('composeGraphics', 'instances[].align.y', ['start', 'center', 'end'])],
    reuseLevels: ['composition', 'poster', 'slide', 'video'],
    delivery: ['GraphicScene and GraphicMotion data'],
    entryPoints: [{ module: 'graphics-composition', exports: ['composeGraphics'], types: ['GraphicInstance', 'GraphicCompositionInput', 'GraphicComposition'] }],
    constraints: ['Uniform fit preserves source geometry; instances share the composition duration.', 'Instance motion must fit the composition duration; object identities are scoped by the compositor.'],
    examples: ['examples/visual-explainer-mdx/shared-graphics-source.ts', 'examples/visual-explainer-mdx/shared-graphics-poster.tsx'],
    dependsOn: ['motion'],
    files: [source('graphics-composition.ts')],
  },
  slides: {
    description: 'Place scenes in themed slides and finite slide sequences.',
    capabilities: ['Wrap a reusable graphic in a titled themed slide', 'Sequence slides with finite timing', 'Query the current slide at authored seconds'],
    primitives: ['slide', 'sequence', 'light', 'dark'],
    variants: [...variants('createSlideScene', 'appearance', ['light', 'dark']), ...variants('createSlideScene', 'preset', ['iso', '3b1b', 'mono-color', 'algebrica'])],
    reuseLevels: ['slide', 'video'],
    delivery: ['React slide view', 'GraphicSlideScene and GraphicSlideSequence data'],
    entryPoints: [{ module: 'graphic-slides', exports: ['createSlideScene', 'sequenceSlides', 'sampleSlideSequence', 'GraphicSlide'], types: ['GraphicSlideScene', 'GraphicSlideSequence'] }],
    constraints: ['Sequence slides must share frame dimensions and have unique IDs.', 'Import themes.css and iso-motion-theme.css; retain the adjacent preset-policy.mjs and preset-policy.d.mts files.'],
    examples: ['examples/visual-explainer-mdx/shared-graphics-slides.tsx', 'examples/visual-explainer-mdx/shared-graphics-source.ts'],
    dependsOn: ['motion'],
    files: [source('graphic-slides.tsx'), source('preset-policy.mjs'), source('preset-policy.d.mts'), {
      source: 'plugins/visual-explainer/templates/iso-motion-theme.css',
      destination: 'iso-motion-theme.css',
    }],
    stylesheets: ['iso-motion-theme.css'],
  },
  video: {
    description: 'Render and control slide sequences with React DOM and GSAP.',
    capabilities: ['Render an initial slide-sequence frame', 'Register a paused GSAP timeline', 'Play, pause, and seek the same authored slide sequence'],
    primitives: ['video-host', 'paused-timeline', 'authoredSeconds'],
    variants: [],
    reuseLevels: ['video'],
    delivery: ['React video host', 'Browser GSAP timeline'],
    entryPoints: [{ module: 'graphic-video', exports: ['GraphicVideo'] }, { module: 'graphic-video-runtime', exports: ['registerGraphicVideo', 'disposeGraphicVideo'] }],
    constraints: ['The current runtime selects one video host per document.', 'Render GraphicVideo before registering; the caller owns timeline control and calls disposeGraphicVideo when the host leaves.', 'Browser playback adds React DOM and GSAP; initial markup uses the same slide sampler.'],
    examples: ['examples/visual-explainer-mdx/shared-graphics-video.tsx', 'examples/visual-explainer-mdx/shared-graphics-source.ts'],
    dependsOn: ['slides'],
    files: [source('graphic-video.tsx'), source('graphic-video-runtime.tsx')],
    dependencies: ['react-dom', 'gsap'],
    devDependencies: ['@types/react-dom'],
  },
  charts: {
    description: 'Render Lieflat rung, unit, barcode, matrix, and thread charts.',
    capabilities: ['Render all five Lieflat chart families', 'Show exact values and encoding explanations', 'Trace records through named stages', 'Adapt React chart layout to available width'],
    primitives: ['rung-bars', 'unit-field', 'barcode', 'bubble-matrix', 'threads'],
    variants: variants('LieflatChart', 'spec.kind', ['rung-bars', 'unit-field', 'barcode', 'bubble-matrix', 'threads']),
    reuseLevels: ['React component'],
    delivery: ['React chart UI'],
    entryPoints: [
      { module: 'lieflat-charts', exports: ['LieflatChart', 'validateLieflatChartSpec'], types: ['BarcodeSpec', 'BubbleMatrixSpec', 'LieflatChartProps', 'LieflatChartSpec', 'RungBarsSpec', 'ThreadsSpec', 'UnitFieldSpec'] },
      { module: 'lieflat-threads', exports: ['ThreadPlot', 'validateThreadsSpec'] },
    ],
    constraints: ['Lieflat React charts do not currently expose a GraphicScene or authored-clock adapter.', 'Browser layout uses ResizeObserver; Vite CSS declarations are required.', 'Chart leaves import their own CSS; the host imports themes.css.'],
    examples: ['examples/visual-explainer-mdx/data-charts.mdx', 'examples/visual-explainer-mdx/lieflat-chart.json', 'examples/visual-explainer-mdx/repair-story-data.ts'],
    dependsOn: ['__threads'],
    files: [source('lieflat-charts.tsx'), source('lieflat-charts.css')],
    dependencies: ['react'],
    devDependencies: ['@types/react', 'vite'],
  },
  'diagram-canvas': {
    description: 'Render an accessible responsive node-and-edge diagram.',
    capabilities: ['Render flow, tree, swimlane, and timeline diagrams', 'Choose horizontal or vertical flow from measured width', 'Expose SVG labels and a readable relationship list'],
    primitives: ['node', 'edge', 'lane', 'date', 'rect', 'oval', 'diamond', 'dot'],
    variants: [...variants('DiagramCanvas', 'layout', ['flow', 'tree', 'swimlane', 'timeline']), ...variants('DiagramCanvas', 'direction', ['auto', 'horizontal', 'vertical']), ...variants('DiagramCanvas', 'nodes[].shape', ['rect', 'oval', 'diamond', 'dot'])],
    reuseLevels: ['React component'],
    delivery: ['React SVG and relationship list'],
    entryPoints: [{ module: 'diagram-canvas', exports: ['DiagramCanvas'], types: ['DiagramCanvasProps', 'DiagramEdge', 'DiagramLane', 'DiagramNode'] }],
    constraints: ['Automatic direction applies to flow layout; other layouts use their authored structure.', 'Browser width adaptation uses ResizeObserver; import themes.css in the host.'],
    examples: ['examples/visual-explainer-mdx/diagram-canvas.mdx', 'examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['diagram'],
    files: [source('diagram-canvas.tsx'), source('diagram-canvas.css')],
  },
  'diagram-walkthrough': {
    description: 'Render original PR Lens architecture/data-flow SVGs, or step through a separately authored diagram.',
    capabilities: ['Preserve the original PR Lens renderer, layout, typography and ordered SMIL pulses', 'Follow edge routes with a moving packet', 'Select previous or next steps and reset playback', 'Pause when hidden and respect reduced motion'],
    primitives: ['edgeId', 'caption', 'durationMs', 'packet', 'previous', 'next', 'play', 'pause', 'reset'],
    variants: [...variants('DiagramWalkthrough', 'layout', ['flow', 'tree', 'swimlane', 'timeline']), ...variants('DiagramWalkthrough', 'direction', ['auto', 'horizontal', 'vertical'])],
    reuseLevels: ['React component'],
    delivery: ['Interactive React diagram'],
    entryPoints: [{ module: 'diagram-walkthrough', exports: ['DiagramWalkthrough'], types: ['DiagramWalkthroughProps', 'DiagramWalkthroughStep'] }, { module: 'pr-lens-figure', exports: ['PrLensFigure', 'prLensExamples'], types: ['PrLensExample'] }],
    constraints: ['Every step references a declared uniquely identified edge and has a caption and positive duration.', 'Playback is a requestAnimationFrame browser interaction, separate from the finite GraphicMotion sampler.', 'Reduced motion keeps manual step navigation; import themes.css in the host.'],
    examples: ['examples/visual-explainer-mdx/animated-diagram.mdx', 'examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__sourceFigure', 'diagram-canvas'],
    files: [source('diagram-walkthrough.tsx'), source('diagram-walkthrough.css'), source('pr-lens-figure.tsx'), source('pr-lens-examples.ts'), source('PR-LENS-LICENSE')],
    dependencies: ['react-dom'],
    devDependencies: ['@types/react-dom'],
  },
  'data-chart': {
    description: 'Render ordinary bar, line, or dot data with exact values.',
    capabilities: ['Compare signed values with bar or dot marks', 'Show a line series with gaps for missing observations', 'Read exact values in an accessible table and narrow layout'],
    primitives: ['bar', 'line', 'dot', 'null', 'valueLabel', 'formatValue'],
    variants: variants('DataChart', 'kind', ['bar', 'line', 'dot']),
    reuseLevels: ['React component'],
    delivery: ['React chart and data table'],
    entryPoints: [{ module: 'charts', exports: ['DataChart'], types: ['ChartDatum', 'DataChartProps'] }],
    constraints: ['Input is a labeled one-dimensional value series; null and nonfinite values display as missing.', 'This React view has no GraphicScene or authored-clock adapter; CSS is imported by the leaf.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__theme'],
    files: [source('charts.tsx'), source('charts.css')],
    dependencies: ['react'],
    devDependencies: ['@types/react', 'vite'],
  },
  'thread-plot': {
    description: 'Trace individual records through named categorical stages.',
    capabilities: ['Draw one thread per record across categorical stages', 'Select a record and read its complete path and note', 'Adapt to portrait layout or offer confined horizontal scrolling'],
    primitives: ['threads', 'stage', 'record', 'path', 'trace'],
    variants: variants('ThreadPlot', 'spec.kind', ['threads']),
    reuseLevels: ['React component'],
    delivery: ['Interactive React chart and record table'],
    entryPoints: [{ module: 'lieflat-threads', exports: ['ThreadPlot', 'validateThreadsSpec'] }, { module: 'lieflat-types', exports: [], types: ['ThreadsSpec'] }],
    constraints: ['Provide two to five unique named stages and up to 250 uniquely identified records with one category per stage.', 'Name the real unit; browser layout uses ResizeObserver. This React view has no GraphicScene or authored-clock adapter.'],
    examples: ['examples/visual-explainer-mdx/repair-story-data.ts', 'examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__threads'],
  },
  'code-block': {
    description: 'Show code with authored line highlights and annotations.',
    capabilities: ['Display escaped source code', 'Attach notes to explicitly numbered source lines', 'Accept caller-prepared highlighted HTML'],
    primitives: ['code', 'language', 'highlightLines', 'annotations', 'html'],
    variants: variants('CodeBlock', 'diff', ['unified']),
    reuseLevels: ['React component'],
    delivery: ['React code figure'],
    entryPoints: [{ module: 'code-blocks', exports: ['CodeBlock'], types: ['CodeBlockProps'] }],
    constraints: ['Syntax-highlighted HTML is caller supplied; no highlighter or export compiler is copied.', 'Caller-supplied html is trusted markup; ordinary code is escaped. Import themes.css in the host.'],
    examples: ['examples/visual-explainer-mdx/code-walkthrough.mdx', 'examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__code'],
  },
  'diff-block': {
    description: 'Compare text using unified or split diff views.',
    capabilities: ['Render a supplied unified patch', 'Compare before and after text', 'Render prepared diff rows with source line numbers'],
    primitives: ['patch', 'before', 'after', 'context', 'add', 'remove', 'hunk'],
    variants: variants('DiffBlock', 'mode', ['unified', 'split']),
    reuseLevels: ['React component'],
    delivery: ['React diff tables'],
    entryPoints: [{ module: 'code-blocks', exports: ['DiffBlock'], types: ['DiffBlockProps', 'DiffRow'] }],
    constraints: ['Supply a patch, before/after text, or prepared rows; this is a display and text comparison component, not a patch applier.', 'Prepared row HTML is trusted markup. Import themes.css in the host.'],
    examples: ['examples/visual-explainer-mdx/diff-terminal-json.mdx', 'examples/visual-explainer-mdx/explain-diff-demo.mdx', 'examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__code'],
  },
  'terminal-block': {
    description: 'Display a terminal transcript with an optional prompt.',
    capabilities: ['Present an authored command/output transcript', 'Show an optional prompt indicator'],
    primitives: ['content', 'title', 'showPrompt'],
    variants: [],
    reuseLevels: ['React component'],
    delivery: ['React preformatted transcript'],
    entryPoints: [{ module: 'code-blocks', exports: ['TerminalBlock'], types: ['TerminalBlockProps'] }],
    constraints: ['Displays text only; it does not run commands or embed a terminal. Import themes.css in the host.'],
    examples: ['examples/visual-explainer-mdx/diff-terminal-json.mdx', 'examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__code'],
  },
  'json-tree': {
    description: 'Explore structured JSON using native expandable branches.',
    capabilities: ['Expand and collapse object and array branches', 'Distinguish string, number, boolean, and null values', 'Choose initial collapsed depth'],
    primitives: ['Object', 'Array', 'string', 'number', 'boolean', 'null', 'collapsedDepth'],
    variants: [],
    reuseLevels: ['React component'],
    delivery: ['React native details tree'],
    entryPoints: [{ module: 'code-blocks', exports: ['JsonTree'], types: ['JsonTreeProps', 'JsonTreeData', 'JsonTreePrimitive', 'JsonTreeRecord'] }],
    constraints: ['Supply JSON-compatible data without cycles; initial branch expansion is controlled by collapsedDepth. Import themes.css in the host.'],
    examples: ['examples/visual-explainer-mdx/diff-terminal-json.mdx', 'examples/visual-explainer-mdx/clean-rich-page.mdx', 'examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__code'],
  },
  quiz: {
    description: 'Ask questions with selectable answers and explanatory feedback.',
    capabilities: ['Select and change an answer', 'Show authored reasons for correct and incorrect answers', 'Report answered questions and score'],
    primitives: ['question', 'option', 'correct', 'why', 'answer', 'score'],
    variants: [],
    reuseLevels: ['React component'],
    delivery: ['Interactive React questions'],
    entryPoints: [{ module: 'code-blocks', exports: ['Quiz'], types: ['QuizProps'] }],
    constraints: ['The caller authors option correctness and feedback; no question generation, persistence, or grading service is copied. Import themes.css in the host.'],
    examples: ['examples/visual-explainer-mdx/clean-rich-page.mdx', 'examples/visual-explainer-mdx/explain-diff-demo.mdx', 'examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__code'],
  },
  pipeline: {
    description: 'Present ordered steps with optional explanatory bodies.',
    capabilities: ['Render an ordered process from strings or titled steps', 'Attach a body to each step'],
    primitives: ['step', 'title', 'body'],
    variants: [],
    reuseLevels: ['React component'],
    delivery: ['React ordered list'],
    entryPoints: [{ module: 'content-blocks', exports: ['Pipeline'], types: ['PipelineProps'] }],
    constraints: ['An authored ordered list, separate from the reusable diagram scene builders. Import themes.css in the host.'],
    examples: ['examples/visual-explainer-mdx/pipeline.mdx', 'examples/visual-explainer-mdx/visual-plan.mdx', 'examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__content'],
  },
  'decision-matrix': {
    description: 'Compare authored rows in a table with inferred columns.',
    capabilities: ['Compare records using the union of their column names', 'Render React content in table cells', 'Confine horizontal table scrolling'],
    primitives: ['row', 'column', 'ReactNode'],
    variants: [],
    reuseLevels: ['React component'],
    delivery: ['React comparison table'],
    entryPoints: [{ module: 'content-blocks', exports: ['DecisionMatrix'], types: ['DecisionMatrixProps'] }],
    constraints: ['Column order follows first appearance in the rows; the component does not rank or score alternatives. Import themes.css in the host.'],
    examples: ['examples/visual-explainer-mdx/interactive.tsx', 'examples/visual-explainer-mdx/visual-plan.mdx', 'examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__content'],
  },
  'risk-ledger': {
    description: 'Show risks with observable signals and mitigations.',
    capabilities: ['Present an authored risk, its signal, and its mitigation', 'Show an optional caller-assigned severity'],
    primitives: ['risk', 'signal', 'mitigation', 'level'],
    variants: variants('RiskLedger', 'risks[].level', ['low', 'medium', 'high']),
    reuseLevels: ['React component'],
    delivery: ['React risk articles'],
    entryPoints: [{ module: 'content-blocks', exports: ['RiskLedger'], types: ['RiskLedgerProps'] }],
    constraints: ['Levels are caller assigned; no risk assessment or probability calculation is copied. Import themes.css in the host.'],
    examples: ['examples/visual-explainer-mdx/visual-plan.mdx', 'examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__content'],
  },
  'sequence-scene': {
    description: 'Build a reusable participant lifeline and message scene.',
    capabilities: ['Draw participant headers and ordered messages', 'Route message arrows and self messages', 'Distinguish dashed message paths'],
    primitives: ['participant', 'lifeline', 'message', 'self-message', 'dashed'],
    variants: [],
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['GraphicScene data'],
    entryPoints: [{ module: 'teaching-scenes', exports: ['createSequenceScene'], types: ['SceneIdentity', 'SceneItem', 'SequenceMessage'] }],
    constraints: ['At least two uniquely identified participants; messages reference declared participants.', 'Scene geometry is authored once; choose responsive composition frames outside the sampler.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__teachingScenes'],
  },
  'state-scene': {
    description: 'Build labeled states and directed transitions as a scene.',
    capabilities: ['Lay out a state graph', 'Route transitions and self transitions', 'Highlight a declared active state'],
    primitives: ['state', 'transition', 'active', 'self-transition'],
    variants: [],
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['GraphicScene data'],
    entryPoints: [{ module: 'teaching-scenes', exports: ['createStateScene'], types: ['SceneIdentity', 'SceneItem', 'StateTransition'] }],
    constraints: ['Transitions and active state must resolve to declared states; at most two transitions may connect a state pair.', 'Finite static geometry; use scene motion for authored focus changes.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__teachingScenes'],
  },
  'layer-scene': {
    description: 'Build an ordered stack of labeled layers as a scene.',
    capabilities: ['Show ordered nested layer rectangles with readable labels', 'Reuse a layer stack in compositions'],
    primitives: ['layer', 'rect', 'label'],
    variants: [],
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['GraphicScene data'],
    entryPoints: [{ module: 'teaching-scenes', exports: ['createLayerScene'], types: ['SceneIdentity', 'SceneItem'] }],
    constraints: ['Supply a nonempty ordered list with unique IDs and nonempty labels; it does not infer system architecture.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__teachingScenes'],
  },
  'plot-scene': {
    description: 'Build reusable line or scatter geometry from observed points.',
    capabilities: ['Plot finite x/y observations with labeled axes', 'Preserve missing-data breaks in line series', 'Emphasize one named series and use explicit domains'],
    primitives: ['series', 'point', 'line', 'scatter', 'null', 'xLabel', 'yLabel', 'domain'],
    variants: variants('createPlotScene', 'variant', ['line', 'scatter']),
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['GraphicScene data'],
    entryPoints: [{ module: 'teaching-scenes', exports: ['createPlotScene'], types: ['SceneIdentity', 'SceneItem', 'PlotPoint', 'PlotSeries', 'PlotSceneInput'] }],
    constraints: ['Provide finite observed points, meaningful axis labels, and increasing domains containing every observation.', 'At most one emphasized series; null breaks lines without interpolation.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__teachingScenes'],
  },
  'token-scene': {
    description: 'Build a labeled token grid with authored acceptance states.',
    capabilities: ['Arrange uniquely identified tokens in columns', 'Distinguish neutral, accepted, and rejected token states'],
    primitives: ['token', 'column', 'neutral', 'accepted', 'rejected'],
    variants: variants('createTokenScene', 'tokens[].state', ['neutral', 'accepted', 'rejected']),
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['GraphicScene data'],
    entryPoints: [{ module: 'chalkboard-figure', exports: ['ChalkboardFigure', 'chalkboardExamples'], types: ['ChalkboardExample'] }, { module: 'teaching-scenes', exports: ['createTokenScene'], types: ['SceneIdentity', 'SceneItem', 'TokenItem'] }],
    constraints: ['Caller assigns token meaning and state; columns must be an integer from 1 to 20.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__sourceFigure', '__teachingScenes'],
    files: [source('chalkboard-figure.tsx'), source('chalkboard-examples.ts'), source('CHALKBOARDING-LICENSE'), source('CHALKBOARDING-FONT-NOTICE.md')],
    dependencies: ['react'],
    devDependencies: ['@types/react'],
  },
  'playhead-scene': {
    description: 'Build a finite event timeline with a reusable playhead.',
    capabilities: ['Place labeled events at authored times', 'Expose a playhead illustration for translation motion'],
    primitives: ['event', 'time', 'duration', 'unit', 'playhead'],
    variants: [],
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['GraphicScene data'],
    entryPoints: [{ module: 'teaching-scenes', exports: ['createPlayheadScene'], types: ['SceneIdentity', 'SceneItem', 'TimedEvent'] }],
    constraints: ['Events must fit a positive finite duration; caller supplies the meaning and time unit.', 'The builder draws the playhead; explicit GraphicMotion translation moves it.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__teachingScenes'],
  },
  'grid-scene': {
    description: 'Build a scalar cell grid using fractional fill and missing marks.',
    capabilities: ['Encode in-domain values as fractional cell fills', 'Mark missing values with a slash', 'Reuse scalar grid geometry in compositions'],
    primitives: ['cell', 'value', 'null', 'domain', 'fractional-fill'],
    variants: [],
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['GraphicScene data'],
    entryPoints: [{ module: 'teaching-scenes', exports: ['createGridScene'], types: ['SceneIdentity', 'GridCell'] }],
    constraints: ['Provide 1–32 columns and at most 1024 uniquely identified cells with finite in-domain values or null.', 'Uses one accent and fraction fill; supply real value meaning and a legend in the host rather than claiming an unexplained heatmap.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__teachingScenes'],
  },
  'reveal-in-order': {
    description: 'Author ordered finite opacity or path-reveal tracks.',
    capabilities: ['Reveal a declared sequence of scene objects', 'Generate deterministic opacity or path-reveal tracks with authored spacing'],
    primitives: ['target', 'opacity', 'reveal', 'duration', 'start', 'step', 'transition'],
    variants: variants('revealInOrder', 'property', ['opacity', 'reveal']),
    reuseLevels: ['scene', 'composition', 'slide', 'video'],
    delivery: ['GraphicMotion data'],
    entryPoints: [{ module: 'teaching-motion', exports: ['revealInOrder'], types: ['OrderedMotionInput'] }],
    constraints: ['Unique targets and finite nonoverlapping steps must fit the motion duration; reveal requires path-only targets.', 'Returns authored tracks for sampleScene; it does not start a clock.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__teachingMotion'],
  },
  'focus-in-order': {
    description: 'Author ordered finite highlight focus with meaningful holds.',
    capabilities: ['Focus declared objects in order', 'Hold each focus until the next authored step', 'Keep the final focus for the remainder of finite motion'],
    primitives: ['target', 'highlight', 'duration', 'start', 'step', 'transition', 'hold'],
    variants: [],
    reuseLevels: ['scene', 'composition', 'slide', 'video'],
    delivery: ['GraphicMotion data'],
    entryPoints: [{ module: 'teaching-motion', exports: ['focusInOrder'], types: ['OrderedMotionInput'] }],
    constraints: ['Unique targets and finite nonoverlapping steps must fit the motion duration.', 'Returns highlight tracks for sampleScene; it does not start a clock.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__teachingMotion'],
  },
  'follow-path': {
    description: 'Traverse prepared routes by distance with exact arrival focus and authored waits.',
    capabilities: ['Prepare bounded line, quadratic, and cubic route geometry', 'Use the same polyline for drawing and normalized distance traversal', 'Compile timestamp arrivals, waits, reverse travel, and trace reveals', 'Hand off focus exactly at authored arrivals'],
    primitives: ['line', 'quadratic', 'cubic', 'distance', 'timestamp', 'wait', 'arrivalFocus', 'trace'],
    variants: [...variants('followPath', 'traversal.mode', ['distance', 'timestamp']), ...variants('prepareGraphicRoute', 'segments[].kind', ['line', 'quadratic', 'cubic'])],
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['Prepared route data', 'GraphicMotion data'],
    entryPoints: [{ module: 'graphic-routes', exports: ['prepareGraphicRoute'], types: ['GraphicPoint', 'GraphicRouteSegment', 'GraphicRouteInput', 'PreparedGraphicRoute'] }, { module: 'teaching-motion', exports: ['followPath'], types: ['RouteTimestamp', 'FollowPathInput'] }],
    constraints: ['Carrier must be an illustration; routes reject zero length, overflow, or unmet finite subdivision budgets.', 'Timestamp keys strictly increase; distances are normalized. Repeated distance means wait.', 'A trace must be the exact prepared path with the same carrier placement and no translation.', 'No DOM geometry, separate renderer, or playback clock.'],
    examples: ['examples/visual-explainer-mdx/motion-review.tsx', 'examples/visual-explainer-mdx/showcase-scenes.ts'],
    dependsOn: ['__teachingMotion'],
  },
  'comparison-wipe': {
    description: 'Compare registered figures using complementary masks on the shared scene clock.',
    capabilities: ['Keep before and after physical geometry aligned', 'Allow changed label content within shared text geometry', 'Intersect animated masks with static and instance frame clips', 'Nest comparisons without changing local routes'],
    primitives: ['before', 'after', 'registration', 'mask', 'x', 'y', 'split'],
    variants: variants('comparisonWipe', 'axis', ['x', 'y']),
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['GraphicScene and GraphicMotion data'],
    entryPoints: [{ module: 'comparison-motion', exports: ['comparisonWipe'], types: ['ComparisonWipeInput'] }],
    constraints: ['Bounds must match exactly and registered IDs must resolve with identical physical geometry, placement, and text metrics including textLength.', 'Use shared layout for unequal labels; no independent refitting or topology morph.', 'Comparison inputs may not already carry mask tracks; static clips are retained.'],
    examples: ['examples/visual-explainer-mdx/motion-review.tsx'],
    dependsOn: ['composition'],
    files: [source('comparison-motion.ts')],
  },
  'code-diff': {
    description: 'Stage readable aligned diffs and identity-preserving edits on the video scene clock.',
    capabilities: ['Align split rows with explicit insertion/deletion gaps', 'Mark literal token changes within a line using one accent and addition/removal signs', 'Fold unchanged context without renumbering source lines', 'Focus individual changes at authored narration intervals', 'Remove retiring parts, move retained characters, then introduce the replacement', 'Use the same scene in posters, slides and encoded review videos'],
    primitives: ['split', 'unified', 'inline-diff', 'context-fold', 'source-line', 'retained-identity', 'edit', 'focus'],
    variants: [...variants('createCodeDiffScene', 'mode', ['split', 'unified']), ...variants('createCodeDiffTransition', 'direction', ['forward', 'reverse'])],
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['Prepared literal diff', 'GraphicScene data', 'Finite GraphicMotion data'],
    entryPoints: [{ module: 'code-diff', exports: ['prepareCodeDiff', 'createCodeDiffScene', 'focusCodeDiff', 'createCodeDiffTransition'], types: ['CodeDiffPart', 'CodeDiffLine', 'CodeDiffRow', 'CodeDiffFold', 'CodeDiffInput', 'PreparedCodeDiff', 'CodeDiffLayout', 'CodeDiffSceneInput', 'CodeDiffFocusBeat', 'PreparedCodeDiffScene', 'CodeDiffTransitionInput', 'PreparedCodeDiffTransition'] }],
    constraints: ['Printable ASCII source with explicit tab-stop expansion; at most 200 lines and 240 expanded columns per version. DiffBlock handles other source text.', 'Supply exact before/after contents and one-based line origins for excerpts. No patch parser, syntax lexer, rename detector or semantic correctness claim.', 'Changed runs align identical trimmed lines, then pair intervening lines in order. Tokens match literal text; repeated tokens use deterministic LCS identities, not AST ownership.', 'Text never shrinks or clips silently: select context/excerpts or author a larger frame. Morph transitions use all source lines and at most 6,000 characters per version; both versions need characters.', 'Focus beats are nonoverlapping half-open intervals. Caller supplies measured cue seconds; there is no narration generator or internal clock.'],
    examples: ['examples/visual-explainer-mdx/code-review-diffs.tsx', 'examples/visual-explainer-mdx/code-review-diffs-source.ts', 'examples/visual-explainer-mdx/code-review-diffs-video.tsx'],
    dependsOn: ['source-range-focus'],
    files: [source('code-diff.ts'), source('diff-lines.mjs'), source('diff-lines.d.mts')],
  },
  'source-range-focus': {
    description: 'Focus exact source ranges and diagram consequences on narration cue intervals.',
    capabilities: ['Prepare literal source character cells with stable semantic part identities', 'Resolve versioned exclusive ranges into exact per-line rectangles', 'Animate source edits while preserving unchanged cell identities', 'Activate range and consequence together on half-open cue intervals', 'Return normalized nonvisual narration provenance receipts'],
    primitives: ['part', 'version', 'character-cell', 'range', 'edit', 'cue', 'start', 'end', 'sourceInterval'],
    variants: [],
    reuseLevels: ['scene', 'composition', 'poster', 'slide', 'video'],
    delivery: ['Prepared source scene', 'GraphicMotion data', 'Narration provenance receipt'],
    entryPoints: [{ module: 'source-scenes', exports: ['createSourceScene'], types: ['SourcePart', 'SourceVersion', 'SourcePosition', 'SourceRange', 'SourceLayout', 'SourceCell', 'SourceSceneInput', 'PreparedSourceScene'] }, { module: 'narrated-motion', exports: ['focusSourceRange', 'editWithIdentity'], types: ['SourceEdit', 'SourceCueBinding', 'SourceCueFocusInput', 'SourceCueFocus'] }],
    constraints: ['Printable ASCII source parts, including explicit spaces; empty lines use empty part arrays. No lexer, tab expansion, or runtime font measurement.', 'Columns are one-based insertion positions and the range end is exclusive. Newline-only and empty ranges reject.', 'Reusing a part ID means identical literal text; edits form a nonoverlapping version chain.', 'A bound cue must remain entirely inside a stable source version. Focus activates at start and clears at end; preserve returned provenance in the film manifest.', 'No narration generation, alignment service, or playback clock. Keep LEMO-LICENSE beside the copied narration source.'],
    examples: ['examples/visual-explainer-mdx/motion-review.tsx'],
    dependsOn: ['motion', 'narration-cues'],
    files: [source('source-scenes.ts'), source('narrated-motion.ts')],
  },
  'authored-values': {
    description: 'Sample scalar or vector parameters with monotone cubic interpolation.',
    capabilities: ['Query deterministic parameter values at finite authored seconds', 'Interpolate monotone cubic values without overshooting adjacent keys', 'Clamp queries to endpoint values', 'Sample vectors with consistent dimensions'],
    primitives: ['ScalarKey', 'VectorKey', 'ValueSampler', 'cubic', 'monotone', 'endpoint', 'authoredSeconds'],
    variants: [],
    reuseLevels: ['authored parameter', 'scene', 'video'],
    delivery: ['Pure TypeScript value samplers'],
    entryPoints: [{ module: 'authored-values', exports: ['createMonotoneTrack', 'createVectorTrack'], types: ['ScalarKey', 'VectorKey', 'ValueSampler'] }],
    constraints: ['Keys need finite values, nonnegative strictly increasing times, and finite interpolation intervals; vector keys need equal nonempty dimensions.', 'Sampled time must be finite and nonnegative. The helper returns parameters; it adds no GraphicMotion property, transform morph, renderer, or clock.', 'Keep the full LEMO-LICENSE and source attribution beside the copied file.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__lemoLicense'],
    files: [source('authored-values.ts')],
  },
  'narration-cues': {
    description: 'Normalize provenance-aware narration cues and serialize SRT or VTT.',
    capabilities: ['Validate caption intervals against a finite audio duration', 'Preserve measured, estimated, or authored alignment provenance', 'Convert aligned words using line-relative offsets', 'Reject overlaps or explicitly truncate the earlier interval', 'Serialize SRT or VTT with carried millisecond rounding'],
    primitives: ['NarrationCue', 'AlignedWord', 'relativeStart', 'relativeEnd', 'offset', 'measured', 'estimated', 'authored', 'srt', 'vtt'],
    variants: [...variants('serializeNarrationCues', 'options.format', ['srt', 'vtt']), ...variants('formatSubtitleTime', 'format', ['srt', 'vtt']), ...variants('normalizeNarrationCues', 'options.overlap', ['error', 'truncate']), ...variants('alignedWordsToCues', 'options.overlap', ['error', 'truncate']), ...variants('serializeNarrationCues', 'options.overlap', ['error', 'truncate'])],
    reuseLevels: ['captions', 'video'],
    delivery: ['Normalized narration cue data', 'SRT and WebVTT text'],
    entryPoints: [{ module: 'narration-cues', exports: ['normalizeNarrationCues', 'alignedWordsToCues', 'formatSubtitleTime', 'serializeNarrationCues'], types: ['NarrationCue', 'CueOptions', 'AlignedWord'] }],
    constraints: ['Cue IDs are unique and nonempty; text, alignment provenance, and positive intervals inside the declared audio duration are required.', 'AlignedWord is [word, relativeStart, relativeEnd]; offset is the narration line start, and word alignment is measured or estimated.', 'Overlap defaults to error. Explicit truncation shortens an earlier cue at the next start; equal starts still fail.', 'No alignment service, audio measurement, speech generation, or playback clock is copied. Keep LEMO-LICENSE beside the source.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__lemoLicense'],
    files: [source('narration-cues.ts')],
  },
  'video-frames': {
    description: 'Plan encoded video frames and inspect loop endpoint closure.',
    capabilities: ['Choose explicit ceil, floor, or nearest frame-count rounding', 'Query frame sample times from duration and FPS', 'Report encoded duration and the last encoded sample separately from the exact endpoint', 'Await detached snapshots to compare loop endpoint closure and last-frame equality'],
    primitives: ['fps', 'rounding', 'frameCount', 'encodedDuration', 'lastFrameTime', 'endpointTime', 'timeAtFrame', 'endpointClosed', 'lastEncodedMatchesStart', 'loop'],
    variants: variants('createVideoFramePlan', 'rounding', ['ceil', 'floor', 'nearest']),
    reuseLevels: ['video', 'frame export', 'loop inspection'],
    delivery: ['Pure TypeScript frame plan', 'Asynchronous sampled-state comparison'],
    entryPoints: [{ module: 'video-frames', exports: ['createVideoFramePlan', 'inspectLoopFrames'], types: ['VideoFramePlan', 'LoopFrameInspection'] }],
    constraints: ['Provide positive finite duration and FPS with explicit rounding; the result must contain a safe positive frame count and finite sample times.', 'Frame indices are integers from zero through frameCount minus one; the exact endpoint is separate from encoded samples.', 'Loop samples must be detached snapshots and equality must return a boolean. State equality does not establish velocity continuity, audio continuity, or pixel quality.', 'The helper plans and inspects samples; the caller owns rendering and encoding.'],
    examples: ['examples/visual-explainer-mdx/component-catalog.tsx'],
    dependsOn: ['__license'],
    files: [source('video-frames.ts')],
  },
});

export const publicBlockIds = Object.freeze(Object.keys(componentRegistry).filter((id) => !componentRegistry[id].hidden));

export function validateRelativePath(value, label = 'Path') {
  if (value !== String(value) || !value || value.includes('\\') || value.includes('\0') || value.startsWith('/') || value.split('/').some((part) => !part || part === '.' || part === '..') || /^[a-z]:/i.test(value)) {
    throw new Error(`${label} must be a confined relative path: ${String(value)}`);
  }
  return value;
}

export function resolveBlocks(ids) {
  if (!Array.isArray(ids) || !ids.length) throw new Error('Select at least one component block.');
  const unknown = ids.filter((id) => !publicBlockIds.includes(id));
  if (unknown.length) throw new Error(`Unknown component block${unknown.length === 1 ? '' : 's'}: ${[...new Set(unknown)].join(', ')}. Run artifacture list.`);
  const blocks = [];
  const visited = new Set();
  const pending = new Set();
  const files = new Map();
  const dependencies = new Set();
  const devDependencies = new Set();
  const stylesheets = new Set();
  const visit = (id) => {
    if (pending.has(id)) throw new Error(`Component dependency cycle: ${id}`);
    if (visited.has(id)) return;
    const block = componentRegistry[id];
    if (!block) throw new Error(`Missing component dependency: ${id}`);
    pending.add(id);
    for (const dependency of block.dependsOn ?? []) visit(dependency);
    for (const file of block.files ?? []) {
      validateRelativePath(file.source, 'Source');
      validateRelativePath(file.destination, 'Destination');
      const previous = files.get(file.destination);
      if (previous && previous.source !== file.source) throw new Error(`Duplicate component destination: ${file.destination}`);
      files.set(file.destination, file);
    }
    for (const name of block.dependencies ?? []) dependencies.add(name);
    for (const name of block.devDependencies ?? []) devDependencies.add(name);
    for (const name of block.stylesheets ?? []) stylesheets.add(name);
    pending.delete(id);
    visited.add(id);
    blocks.push(id);
  };
  ids.forEach(visit);
  return { blocks, files: [...files.values()], dependencies: [...dependencies], devDependencies: [...devDependencies], stylesheets: [...stylesheets] };
}
