"""Regenerate visual-explainer-mdx/text-metrics-data.ts from the bundled fonts.

Run: uvx --from 'fonttools==4.53.1' python scripts/text-metrics/build.py
Advance widths are stored per em for regular (400) and semibold (600) instances.
"""
import json
import pathlib

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = pathlib.Path(__file__).resolve().parents[2]
FONTS = {
    'Inter': 'scripts/video-engines/fonts/Inter[opsz,wght].ttf',
    'EB Garamond': 'scripts/video-engines/fonts/EBGaramond[wght].ttf',
    'Geist Mono': 'scripts/video-engines/fonts/GeistMono.ttf',
    'Space Mono': 'scripts/video-engines/fonts/SpaceMono-Regular.ttf',
    'STIX Two Math': 'scripts/video-engines/fonts/STIXTwoMath-Regular.ttf',
}
CHARS = ''.join(chr(c) for c in range(32, 127)) + '’‘“”—–…•·×÷→←↑↓✓✗±≤≥≠°€£'


def widths(font):
    cmap, hmtx, upem = font.getBestCmap(), font['hmtx'], font['head'].unitsPerEm
    table = {}
    for ch in CHARS:
        glyph = cmap.get(ord(ch))
        if glyph is not None:
            table[ch] = round(hmtx[glyph][0] / upem, 4)
    return table


def instance(path, weight):
    font = TTFont(ROOT / path)
    if 'fvar' in font:
        axes = {axis.axisTag: axis for axis in font['fvar'].axes}
        location = {tag: (min(max(weight, axis.minValue), axis.maxValue) if tag == 'wght' else axis.defaultValue) for tag, axis in axes.items()}
        font = instancer.instantiateVariableFont(font, location)
    return font


data = {}
for family, path in FONTS.items():
    regular = widths(instance(path, 400))
    semibold = widths(instance(path, 600))
    data[family] = {'400': regular, '600': semibold if semibold != regular else None}

out = ROOT / 'visual-explainer-mdx/text-metrics-data.ts'
out.write_text('// Generated by scripts/text-metrics/build.py from the bundled OFL fonts. Do not edit by hand.\n'
               '// Advance widths per em, keyed by family, then weight, then character.\n'
               f'export const fontAdvances = {json.dumps(data, ensure_ascii=False, separators=(",", ":"))} satisfies Record<string, Record<\'400\' | \'600\', Record<string, number> | null>>;\n')
print(out, out.stat().st_size, 'bytes')
