import React, { useEffect, useState, type ReactNode } from 'react';
import { createGraphicScene } from '../../visual-explainer-mdx/graphics-types';
import { createVectorTrack } from '../../visual-explainer-mdx/authored-values';
import { normalizeNarrationCues, serializeNarrationCues } from '../../visual-explainer-mdx/narration-cues';
import { createVideoFramePlan, inspectLoopFrames, type LoopFrameInspection } from '../../visual-explainer-mdx/video-frames';
import { GraphicCanvas } from '../../visual-explainer-mdx/graphics';
import { sampleScene, defineGraphicMotion } from '../../visual-explainer-mdx/graphic-motion';
import { createSequenceScene, createStateScene, createLayerScene, createPlotScene, createTokenScene, createPlayheadScene, createGridScene } from '../../visual-explainer-mdx/teaching-scenes';
import { revealInOrder, focusInOrder } from '../../visual-explainer-mdx/teaching-motion';
import { DataChart } from '../../visual-explainer-mdx/charts';
import { LieflatChart } from '../../visual-explainer-mdx/lieflat-charts';
import { ThreadPlot } from '../../visual-explainer-mdx/lieflat-threads';
import { DagCanvas } from '../../visual-explainer-mdx/dag-canvas';
import { dagInput } from './dag-source';
import { DiagramCanvas } from '../../visual-explainer-mdx/diagram-canvas';
import { DiagramWalkthrough } from '../../visual-explainer-mdx/diagram-walkthrough';
import { CodeBlock, DiffBlock, TerminalBlock, JsonTree, Quiz } from '../../visual-explainer-mdx/code-blocks';
import { Pipeline, DecisionMatrix, RiskLedger } from '../../visual-explainer-mdx/content-blocks';
import type { GraphicScene } from '../../visual-explainer-mdx/graphics-types';
import type { GraphicMotion } from '../../visual-explainer-mdx/graphic-motion';
import type { LieflatChartSpec } from '../../visual-explainer-mdx/lieflat-types';
import '../../visual-explainer-mdx/themes.css';
import './component-catalog.css';

const identity = (id: string, title: string, description: string) => ({ id, title, description });
const actors = [{ id: 'client', label: 'Client' }, { id: 'handler', label: 'Handler' }, { id: 'store', label: 'Storage' }];
const sequence = createSequenceScene({ ...identity('messages', 'A request and its response', 'Client sends a request to the handler. Handler queries storage, receives rows, and returns the response.'), participants: actors, messages: [
  { id: 'request', from: 'client', to: 'handler', label: 'Validated request' },
  { id: 'query', from: 'handler', to: 'store', label: 'Read records' },
  { id: 'rows', from: 'store', to: 'handler', label: 'Matching rows', dashed: true },
  { id: 'response', from: 'handler', to: 'client', label: 'Response', dashed: true },
] });
const states = createStateScene({ ...identity('states', 'A retry has a condition', 'Waiting advances to running. Success completes the job. Failure returns it to waiting for another attempt.'), states: [{ id: 'waiting', label: 'Waiting' }, { id: 'running', label: 'Running' }, { id: 'done', label: 'Complete' }], transitions: [
  { id: 'start', from: 'waiting', to: 'running', label: 'Start' }, { id: 'finish', from: 'running', to: 'done', label: 'Succeeded' }, { id: 'retry', from: 'running', to: 'waiting', label: 'Failed: retry' },
] });
const layers = createLayerScene({ ...identity('layers', 'Containment communicates ownership', 'Video contains a slide, which contains a diagram made of graphic primitives.'), layers: [{ id: 'video', label: 'Video: authored timeline' }, { id: 'slide', label: 'Slide: frame and explanation' }, { id: 'diagram', label: 'Diagram: relationships' }, { id: 'graphics', label: 'Graphics: geometry and text' }] });
const plot = createPlotScene({ ...identity('cost-curve', 'Plots retain missing observations', 'Illustrative request latency observations. A missing third observation breaks the line rather than inventing a value.'), xLabel: 'Request number', yLabel: 'Latency (ms)', series: [{ id: 'latency', label: 'Illustrative latency; gap means unobserved', emphasis: true, points: [{ x: 1, y: 8 }, { x: 2, y: 12 }, null, { x: 4, y: 18 }, { x: 5, y: 9 }] }] });
const scatter = createPlotScene({ ...identity('scatter', 'Compare numeric measurements', 'Illustrative cost and quality pairs shown as independent observations.'), variant: 'scatter', xLabel: 'Illustrative cost', yLabel: 'Illustrative quality', series: [{ id: 'observations', label: 'Measured pairs', points: [{ x: 1, y: 2 }, { x: 2, y: 4 }, { x: 3, y: 3 }, { x: 4, y: 7 }, { x: 5, y: 6 }] }] });
const tokens = createTokenScene({ ...identity('token-sequence', 'Reveal one token at a time', 'A token sequence shows which proposals were accepted and which was rejected. Rejection has a strike as well as a neutral color.'), tokens: [{ id: 'a', label: 'The', state: 'accepted' }, { id: 'b', label: 'model', state: 'accepted' }, { id: 'c', label: 'guesses', state: 'rejected' }, { id: 'd', label: 'predicts', state: 'accepted' }, { id: 'e', label: 'a token' }], columns: 5 });
const playhead = createPlayheadScene({ ...identity('events', 'Events share a numeric time axis', 'Illustrative request events at 0, 2, and 5 seconds. One playhead moves from zero to six seconds.'), events: [{ id: 'receive', label: 'Receive', time: 0 }, { id: 'validate', label: 'Validate', time: 2 }, { id: 'respond', label: 'Respond', time: 5 }], duration: 6, unit: 's' });
const grid = createGridScene({ ...identity('scalar-field', 'A scalar field uses one accent', 'Illustrative values from zero to one fill a fraction of each cell; slashes mean missing values.'), columns: 12, domain: [0, 1], cells: Array.from({ length: 72 }, (_, i) => ({ id: String(i), value: i === 20 || i === 41 ? null : ((i * 17 + 3) % 73) / 72 })) });
const parameterTrack = createVectorTrack([[0, [0, 0]], [2, [130, 0]], [4, [480, 0]], [6, [480, 0]]]);
const narrationCues = normalizeNarrationCues([
  { id: 'receive', start: 0, end: 2, text: 'Receive a request.', alignment: 'authored' },
  { id: 'validate', start: 2, end: 4, text: 'Validate the data.', alignment: 'authored' },
  { id: 'respond', start: 4, end: 6, text: 'Return the result.', alignment: 'authored' },
], { duration: 6 });
const subtitleText = serializeNarrationCues(narrationCues, { duration: 6, format: 'vtt' });
const loopPlan = createVideoFramePlan({ duration: 1.07, fps: 24, rounding: 'ceil' });
const loopPosition = (seconds: number) => ({ x: Math.cos(seconds / loopPlan.duration * Math.PI * 2), y: Math.sin(seconds / loopPlan.duration * Math.PI * 2) });
const loopFrames = [0, loopPlan.lastFrameTime, loopPlan.endpointTime].map((seconds, index) => {
  const point = loopPosition(seconds);
  return createGraphicScene({ ...identity(`loop-${index}`, `Loop at ${seconds.toFixed(4)} seconds`, 'A point follows a circle. Exact endpoint closure is checked separately from the last encoded sample.'), bounds: { x: 0, y: 0, width: 200, height: 200 }, objects: [
    { id: 'route', kind: 'illustration', primitives: [{ kind: 'circle', x: 100, y: 100, radius: 70, fill: 'none', stroke: 'frame', strokeRole: 'guide' }] },
    { id: 'point', kind: 'illustration', primitives: [{ kind: 'circle', x: 100 + point.x * 70, y: 100 + point.y * 70, radius: 5, fill: 'accent' }] },
  ] });
});
const sceneExamples: { title: string; description: string; api: string; block: string; graphic: GraphicScene; motion?: GraphicMotion }[] = [
  { title: 'Sequence messages', description: 'Participants keep their lanes. Requests and responses own separate IDs and labels.', api: 'createSequenceScene', block: 'sequence-scene', graphic: sequence, motion: revealInOrder(sequence, { targets: ['request', 'query', 'rows', 'response'].flatMap(id => [`message:${id}`, `message-label:${id}`]), duration: 6, transition: .2 }) },
  { title: 'State transitions', description: 'Show a cycle and its exit conditions. The current state can receive focus without moving its connectors.', api: 'createStateScene', block: 'state-scene', graphic: states, motion: focusInOrder(states, { targets: ['node:waiting', 'node:running', 'node:done'], duration: 6, start: 0, step: 1.8, transition: .25 }) },
  { title: 'Nested layers', description: 'Containment explains which layer owns another. Reuse the whole scene or compose it into a frame.', api: 'createLayerScene', block: 'layer-scene', graphic: layers, motion: revealInOrder(layers, { targets: layers.objects.map(object => object.id), duration: 6, step: 1.2 }) },
  { title: 'Line plots', description: 'Numeric domains and stable series IDs. Missing observations break paths; they never become interpolated data.', api: 'createPlotScene', block: 'plot-scene', graphic: plot, motion: revealInOrder(plot, { targets: ['series:latency'], property: 'reveal', duration: 6, start: .3, transition: 3 }) },
  { title: 'Scatter plots', description: 'Use independent marks for paired numeric observations, with meaningful axis labels.', api: 'createPlotScene', block: 'plot-scene', graphic: scatter },
  { title: 'Token sequences', description: 'Reveal serial or batched decisions. Accepted tokens use the accent; a strike distinguishes rejected tokens.', api: 'createTokenScene', block: 'token-scene', graphic: tokens, motion: revealInOrder(tokens, { targets: tokens.objects.map(object => object.id), duration: 6, step: .8 }) },
  { title: 'Timed events', description: 'A playhead is a translated illustration on one authored clock. Seeking backwards returns the same frame.', api: 'createPlayheadScene', block: 'playhead-scene', graphic: playhead, motion: defineGraphicMotion(playhead, { duration: 6, tracks: [{ target: 'playhead', property: 'translation', start: 0, duration: 6, from: { x: 0, y: 0 }, to: { x: 480, y: 0 }, ease: 'linear' }] }) },
  { title: 'Scalar grids', description: 'Fill height encodes values from zero to one; slashes encode missing observations. The data and animation remain separate.', api: 'createGridScene', block: 'grid-scene', graphic: grid, motion: revealInOrder(grid, { targets: grid.objects.map(object => object.id), duration: 6, transition: .035, step: .075 }) },
];
const chartSpecs: { title: string; spec: LieflatChartSpec }[] = [
  { title: 'Rung bars', spec: { kind: 'rung-bars', unit: 2, unitLabel: 'requests per rung', data: [{ label: 'Validated', value: 9 }, { label: 'Queued', value: 5 }, { label: 'Unobserved', value: null }] } },
  { title: 'Unit fields', spec: { kind: 'unit-field', unit: 1, unitLabel: 'requests per square', data: [{ label: 'Complete', value: 12 }, { label: 'Pending', value: 7.5 }] } },
  { title: 'Barcodes', spec: { kind: 'barcode', valueLabel: 'Requests', data: [{ date: '2026-10-01', value: 8 }, { date: '2026-10-02', value: null, note: 'Unobserved' }, { date: '2026-10-03', value: 12 }, { date: '2026-10-04', value: 6 }] } },
  { title: 'Bubble matrices', spec: { kind: 'bubble-matrix', valueLabel: 'Requests', data: [{ row: 'API', column: 'Complete', value: 8 }, { row: 'API', column: 'Pending', value: 2 }, { row: 'Worker', column: 'Complete', value: 5 }, { row: 'Worker', column: 'Pending', value: null }] } },
  { title: 'Record threads', spec: { kind: 'threads', unitLabel: 'Requests', stages: ['Received', 'Checked', 'Outcome'], records: [{ id: 'a', path: ['API', 'Valid', 'Complete'] }, { id: 'b', path: ['API', 'Valid', 'Pending'] }, { id: 'c', path: ['Worker', 'Invalid', 'Returned'] }] } },
];
const diagramNodes = [{ id: 'request', label: 'Request' }, { id: 'handler', label: 'Handler' }, { id: 'storage', label: 'Storage' }];
const diagramEdges = [{ id: 'validate', from: 'request', to: 'handler', label: 'Validate' }, { id: 'read', from: 'handler', to: 'storage', label: 'Read' }];
function Example({ title, description, command, children }: { title: string; description?: string; command?: string; children: ReactNode }) {
  return <article className="catalog-example"><h3>{title}</h3>{description ? <p>{description}</p> : null}<div className="catalog-preview">{children}</div>{command ? <details><summary>Copy this block</summary><pre><code>{command}</code></pre></details> : null}</article>;
}
export default function ComponentCatalog() {
  const [preset, setPreset] = useState('iso'), [time, setTime] = useState(6);
  const [loopInspection, setLoopInspection] = useState<LoopFrameInspection>();
  useEffect(() => {
    let mounted = true;
    inspectLoopFrames({ plan: loopPlan, sample: loopPosition, equal: (a, b) => Math.hypot(a.x - b.x, a.y - b.y) < 1e-10 }).then(result => { if (mounted) setLoopInspection(result); });
    return () => { mounted = false; };
  }, []);
  const [panX, panY] = parameterTrack(time);
  const parameterScene = createGraphicScene({ ...playhead, id: 'monotone-playhead', objects: playhead.objects.map(object => object.id === 'playhead' ? { ...object, state: { opacity: 1, reveal: 1, highlight: false, x: panX, y: panY } } : object) });
  const currentCue = narrationCues.find(cue => cue.start <= time && time < cue.end);
  return <main className="component-catalog" data-ve-preset={preset} data-ve-theme={preset === '3b1b' ? 'dark' : 'light'}>
    <header><h1>Reusable visual components</h1><p>Start with an existing block. Combine geometry, relationships, and authored motion into diagrams, slides, and video. These previews render the actual local components with illustrative data.</p></header>
    <div className="catalog-controls"><label>Theme <select value={preset} onChange={event => setPreset(event.target.value)}><option value="iso">ISO</option><option value="3b1b">3b1b</option><option value="mono-color">Mono Color</option><option value="algebrica">Algebrica</option></select></label><label>Authored time <input aria-label="Authored time" type="range" min="0" max="6" step=".05" value={time} onChange={event => setTime(Number(event.target.value))} /><output>{time.toFixed(2)} s</output></label></div>
    <nav aria-label="Components"><a href="/iso/">ISO motion</a><a href="#scenes">Scenes and motion</a><a href="#diagrams">Diagrams</a><a href="#charts">Charts</a><a href="#code">Code and interaction</a><a href="#content">Structured explanations</a></nav>
    <section id="scenes"><h2>Scenes and motion</h2><p>Every scene below is plain validated data rendered by <code>GraphicCanvas</code>. Move the time control to inspect ordered reveal, focus, path drawing, and playhead translation.</p><div className="catalog-grid">{sceneExamples.map(example => <Example key={example.title} title={example.title} description={example.description} command={`artifacture add ${example.block}${example.motion ? ' motion' : ''} --cwd ./my-explainer\nimport { ${example.api} } from './artifacture/teaching-scenes';`}><GraphicCanvas scene={example.motion ? sampleScene(example.graphic, example.motion, time) : example.graphic} /></Example>)}</div><div className="catalog-grid"><Example title="Monotone parameter tracks" description="A cubic parameter track advances the playhead without overshoot, then holds from four to six seconds. The caller supplies authored time." command="artifacture add authored-values playhead-scene --cwd ./my-explainer"><GraphicCanvas scene={parameterScene} /></Example><Example title="Narration cues and subtitles" description="These authored example cues use the same six-second clock. Measured word alignments retain their source intervals and provenance." command="artifacture add narration-cues --cwd ./my-explainer"><p data-narration-preview aria-live="polite">{currentCue?.text ?? 'Narration complete.'}</p><details><summary>Inspect the WebVTT output</summary><pre><code>{subtitleText}</code></pre></details></Example></div></section>
    <Example title="Frame plans and loop endpoints" description="A 1.07-second loop at 24 fps uses ceil rounding to cover its duration. Its last encoded sample precedes the exact endpoint. Inspect both instead of treating them as the same frame." command="artifacture add video-frames --cwd ./my-explainer"><div className="loop-frame-previews">{loopFrames.map((frame, index) => <figure key={frame.id}><GraphicCanvas scene={frame} /><figcaption>{['Start', 'Last encoded frame', 'Exact endpoint'][index]} · {[0, loopPlan.lastFrameTime, loopPlan.endpointTime][index].toFixed(4)} s</figcaption></figure>)}</div><p data-loop-inspection>{loopInspection ? `Endpoint closed: ${loopInspection.endpointClosed ? 'yes' : 'no'}. Last encoded frame matches start: ${loopInspection.lastEncodedMatchesStart ? 'yes' : 'no'}. ${loopPlan.frameCount} frames cover ${loopPlan.encodedDuration.toFixed(4)} seconds.` : 'Comparing sampled positions…'}</p></Example>
    <section id="diagrams"><h2>Diagrams</h2><div className="catalog-grid"><Example title="Dependency DAG" description="Trace multi-parent dependencies with pointer or keyboard focus. The same graph becomes a scene, slide, or authored reveal." command="artifacture add dag --cwd ./my-explainer"><DagCanvas {...dagInput} initialSelection="composition" /></Example>{(['flow', 'tree', 'swimlane', 'timeline'] as const).map(layout => <Example key={layout} title={layout.charAt(0).toUpperCase() + layout.slice(1)} command="artifacture add diagram-canvas --cwd ./my-explainer"><DiagramCanvas nodes={diagramNodes} edges={diagramEdges} layout={layout} direction="horizontal" title={`${layout} request path`} lanes={layout === 'swimlane' ? [{ id: 'service', label: 'Service' }] : undefined} dates={layout === 'timeline' ? ['Receive', 'Validate', 'Read'] : undefined} /></Example>)}<Example title="Step through a relationship" description="Play a packet trace or inspect individual steps. Reduced motion uses manual steps." command="artifacture add diagram-walkthrough --cwd ./my-explainer"><DiagramWalkthrough nodes={diagramNodes} edges={diagramEdges} direction="horizontal" title="Request walkthrough" steps={[{ edgeId: 'validate', caption: 'The handler validates the incoming request.' }, { edgeId: 'read', caption: 'Only a validated request reaches storage.' }]} /></Example></div></section>
    <section id="charts"><h2>Charts</h2><p>Choose an encoding for the question. These React charts provide exact values and narrow-screen views; authored data transitions are a separate adapter.</p><div className="catalog-grid">{(['bar', 'line', 'dot'] as const).map(kind => <Example key={kind} title={`${kind.charAt(0).toUpperCase() + kind.slice(1)} chart`} command="artifacture add data-chart --cwd ./my-explainer"><DataChart kind={kind} title="Illustrative requests" valueLabel="Requests" data={[{ label: 'Received', value: 12 }, { label: 'Checked', value: 9 }, { label: 'Missing', value: null }, { label: 'Complete', value: 7 }]} /></Example>)}{chartSpecs.map(chart => <Example key={chart.title} title={chart.title} command={`artifacture add ${chart.spec.kind === 'threads' ? 'thread-plot' : 'charts'} --cwd ./my-explainer`}>{chart.spec.kind === 'threads' ? <ThreadPlot spec={chart.spec} /> : <LieflatChart title={`Illustrative ${chart.title.toLowerCase()}`} spec={chart.spec} />}</Example>)}</div></section>
    <section id="code"><h2>Code and interaction</h2><div className="catalog-grid"><Example title="Annotated code" command="artifacture add code-block --cwd ./my-explainer"><CodeBlock language="tsx" filename="scene.ts" code={'const scene = createDiagramScene({\n  id: "request-path",\n  nodes,\n  edges,\n});'} annotations={[{ line: 2, note: 'Stable scene identity survives each output.' }]} /></Example>{(['unified', 'split'] as const).map(mode => <Example key={mode} title={`${mode} diff`} command="artifacture add diff-block --cwd ./my-explainer"><DiffBlock before={'const result = read(request);'} after={'const valid = validate(request);\nconst result = read(valid);'} language="ts" filename="handler.ts" mode={mode} /></Example>)}<Example title="Command transcript" command="artifacture add terminal-block --cwd ./my-explainer"><TerminalBlock content={'artifacture list --query "sequence"\nartifacture add sequence-scene motion --cwd ./demo'} /></Example><Example title="Expandable scene data" command="artifacture add json-tree --cwd ./my-explainer"><JsonTree data={{ id: 'request-path', bounds: { width: 720, height: 400 }, nodes: ['Request', 'Handler', 'Storage'], edges: ['validate', 'read'] }} collapsedDepth={1} /></Example><Example title="Check understanding" command="artifacture add quiz --cwd ./my-explainer"><Quiz questions={[{ q: 'Which layer owns authored time?', options: [{ text: 'Graphic primitives', why: 'Primitives describe geometry; they do not run a clock.' }, { text: 'Motion tracks', correct: true, why: 'Tracks map explicit seconds to changes on stable object IDs.' }, { text: 'Theme', why: 'The theme owns paint, stroke, and typography roles.' }] }]} /></Example></div></section>
    <section id="content"><h2>Structured explanations</h2><Example title="Ordered steps" command="artifacture add pipeline --cwd ./my-explainer"><Pipeline steps={[{ title: 'Find', body: 'Search the index for an existing capability.' }, { title: 'Copy', body: 'Install its editable source and transitive dependencies.' }, { title: 'Compose', body: 'Fit scenes into frames; bind motion to authored time.' }]} /></Example><Example title="Compare choices" command="artifacture add decision-matrix --cwd ./my-explainer"><DecisionMatrix rows={[{ Question: 'Which request runs when?', Block: 'Sequence scene', Reason: 'Message order and participant lanes' }, { Question: 'What can happen next?', Block: 'State scene', Reason: 'Transitions and their conditions' }, { Question: 'How does a value change?', Block: 'Line plot', Reason: 'Numeric position and gaps' }]} /></Example><Example title="Document a concrete risk" command="artifacture add risk-ledger --cwd ./my-explainer"><RiskLedger risks={[{ risk: 'An animation bridges an unobserved value', signal: 'A line passes through a missing measurement.', mitigation: 'Keep missing samples as null; the plot breaks its path.' }]} /></Example></section>
  </main>;
}
